import * as stylex from '@stylexjs/stylex'

export const catalogKineticStyles = stylex.create({
  rangeControl: {
    borderRadius: 'calc(var(--control-radius) + 4px)',
    height: 42,
    outline: { ':focus-within': '2px solid var(--control-accent)' },
    outlineOffset: { ':focus-within': 3 },
    position: 'relative',
  },
  rangeValue: (value: string) => ({ '--catalog-range-value': value }),
  rangeInput: {
    appearance: 'none',
    cursor: 'pointer',
    height: '100%',
    inset: 0,
    margin: 0,
    opacity: 0,
    position: 'absolute',
    width: '100%',
    zIndex: 2,
  },
  rangeRail: {
    backgroundColor: 'color-mix(in srgb, var(--kinetic-background) 78%, var(--kinetic-foreground))',
    borderColor: 'var(--control-border)',
    borderRadius: 999,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 1px 2px 3px color-mix(in srgb, var(--kinetic-shadow-color) 52%, transparent), inset -1px -1px 0 color-mix(in srgb, white 22%, transparent)',
    height: 6,
    left: 9,
    overflow: 'visible',
    position: 'absolute',
    right: 9,
    top: 18,
  },
  rangeFill: {
    backgroundColor: 'var(--kinetic-accent)',
    borderRadius: 999,
    display: 'block',
    height: '100%',
    width: 'var(--catalog-range-value)',
  },
  rangeKnob: {
    backgroundColor: 'color-mix(in srgb, var(--kinetic-background) 92%, white)',
    borderColor: 'var(--kinetic-foreground)',
    borderRadius: 'max(2px, calc(var(--kinetic-radius) * 0.4))',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 1px 1px 0 color-mix(in srgb, white 48%, transparent), inset -1px -1px 0 var(--kinetic-edge-shadow), 1px 2px 0 color-mix(in srgb, var(--kinetic-shadow-color) 54%, transparent), 2px 4px 7px color-mix(in srgb, var(--kinetic-shadow-color) 28%, transparent)',
    display: 'block',
    height: 24,
    left: 'var(--catalog-range-value)',
    position: 'absolute',
    top: '50%',
    transform: 'translate(-50%, -50%)',
    transition: 'left 90ms linear',
    width: 18,
  },
  rangeKnobMark: {
    backgroundColor: 'color-mix(in srgb, var(--kinetic-foreground) 32%, transparent)',
    display: 'block',
    height: 10,
    left: 'calc(50% - 1px)',
    position: 'absolute',
    top: 6,
    width: 2,
  },
  choiceInput: {
    appearance: 'none',
    backgroundColor: {
      default: 'color-mix(in srgb, var(--kinetic-background) 92%, white)',
      ':checked': 'var(--kinetic-accent)',
    },
    borderColor: 'var(--kinetic-foreground)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default:
        'inset 1px 1px 0 color-mix(in srgb, white 54%, transparent), inset -1px -1px 0 var(--kinetic-edge-shadow), min(2px, var(--kinetic-shadow-x)) 3px 0 color-mix(in srgb, var(--kinetic-shadow-color) 56%, transparent)',
      ':checked':
        'inset 1px 1px 0 color-mix(in srgb, white 46%, transparent), inset -1px -1px 0 var(--kinetic-edge-shadow), min(2px, var(--kinetic-shadow-x)) 3px 0 color-mix(in srgb, var(--kinetic-accent) 48%, var(--kinetic-shadow-color))',
    },
    cursor: 'pointer',
    height: 18,
    opacity: { ':disabled': 0.4 },
    outline: { ':focus-visible': '2px solid var(--kinetic-accent)' },
    outlineOffset: { ':focus-visible': 3 },
    transform: {
      ':active': 'translate(var(--kinetic-control-press-x), var(--kinetic-control-press))',
    },
    transition: 'var(--generated-button-transition)',
    width: 18,
  },
  checkbox: {
    backgroundImage: {
      default: 'none',
      ':checked':
        'linear-gradient(135deg, transparent 38%, var(--kinetic-background) 39% 55%, transparent 56%)',
    },
    borderRadius: 'max(2px, calc(var(--control-radius) * 0.35))',
  },
  radio: {
    backgroundImage: {
      default: 'none',
      ':checked': 'radial-gradient(circle, var(--kinetic-background) 0 27%, transparent 30%)',
    },
    borderRadius: '50%',
  },
  denseTable: { marginTop: 16 },
  denseTableRow: {
    backgroundColor: {
      default: 'transparent',
      ':hover': 'color-mix(in srgb, var(--kinetic-accent) 8%, var(--kinetic-background))',
    },
    transition: 'background-color 140ms ease',
  },
  denseIdentity: { alignItems: 'flex-start', display: 'flex', gap: 13 },
  denseOrdinal: {
    alignItems: 'center',
    backgroundColor: 'var(--kinetic-foreground)',
    color: 'var(--kinetic-background)',
    display: 'inline-flex',
    flex: '0 0 auto',
    fontFamily: 'var(--guide-mono, ui-monospace, monospace)',
    fontSize: '0.65rem',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  denseStack: { display: 'grid', gap: 5, minWidth: 0 },
  denseMeta: {
    color: 'color-mix(in srgb, var(--kinetic-foreground) 58%, transparent)',
    fontFamily: 'var(--guide-mono, ui-monospace, monospace)',
    fontSize: '0.63rem',
    fontWeight: 500,
    letterSpacing: '0.045em',
    overflowWrap: 'anywhere',
    textTransform: 'uppercase',
  },
  denseReason: { lineHeight: 1.45, margin: 0 },
  denseState: {
    borderColor: 'currentColor',
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'inline-flex',
    fontSize: '0.64rem',
    fontWeight: 900,
    letterSpacing: '0.08em',
    padding: '5px 7px',
    textTransform: 'uppercase',
  },
  denseStateReady: {
    backgroundColor: 'var(--kinetic-foreground)',
    color: 'var(--kinetic-background)',
  },
  denseStateReview: { color: 'var(--kinetic-accent)' },
})
