import * as stylex from '@stylexjs/stylex'
import { className, sharedStyles } from './shared.stylex'

export const catalogStyles = stylex.create({
  root: {
    '--control-surface': 'var(--generated-control-surface, rgb(255 255 255 / 0.72))',
    '--control-surface-strong': 'var(--generated-control-surface-strong, #fff)',
    '--control-border': 'var(--generated-control-border, rgb(20 20 20 / 0.24))',
    '--control-text': 'var(--generated-control-text, currentColor)',
    '--control-muted': 'var(--generated-control-muted, rgb(20 20 20 / 0.62))',
    '--control-accent': 'var(--generated-control-accent, #5a4ff0)',
    '--control-accent-contrast': 'var(--generated-control-accent-contrast, #fff)',
    '--control-shadow': 'var(--generated-control-shadow, 0 18px 45px rgb(0 0 0 / 0.12))',
    color: 'var(--control-text)',
  },
  grid: {
    display: 'grid',
    gap: 16,
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    '@media (max-width: 980px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '@media (max-width: 680px)': { gridTemplateColumns: '1fr' },
  },
  surface: {
    backdropFilter: 'var(--control-backdrop-filter, none)',
    backgroundColor: 'var(--control-surface)',
    borderColor: 'var(--control-border)',
    borderRadius: 'var(--control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: 'var(--control-shadow)',
  },
  specimen: { minHeight: 185, padding: 24 },
  specimenWide: {
    gridColumn: 'span 2',
    '@media (max-width: 680px)': { gridColumn: 'auto' },
  },
  cardFirstWide: {
    '@media (max-width: 980px)': { gridColumn: 'span 2' },
    '@media (max-width: 680px)': { gridColumn: 'auto' },
  },
  rowHeader: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  specimenHeader: {
    borderBottomColor: 'var(--control-border)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    marginBottom: 34,
    paddingBottom: 12,
  },
  label: {
    fontSize: '0.7rem',
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  code: {
    color: 'var(--control-muted)',
    fontFamily: 'var(--guide-mono, ui-monospace, monospace)',
    fontSize: '0.68rem',
  },
  controlRow: { alignItems: 'center', display: 'flex', flexWrap: 'wrap', gap: 10 },
  interactive: {
    color: 'inherit',
    cursor: 'pointer',
    outline: { ':focus-visible': '3px solid var(--control-accent)' },
    outlineOffset: { ':focus-visible': 3 },
  },
  button: {
    backdropFilter: 'var(--control-interactive-backdrop-filter, none)',
    backgroundColor: 'var(--control-surface-strong)',
    backgroundImage:
      'var(--generated-button-background, linear-gradient(180deg, rgb(255 255 255 / 0.1), transparent 36%))',
    borderColor: 'var(--control-border)',
    borderRadius: 'var(--control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default:
        'var(--generated-button-shadow, inset 0 1px 0 rgb(255 255 255 / 0.22), inset 0 -1px 0 rgb(0 0 0 / 0.08), 0 2px 0 rgb(0 0 0 / 0.1), 0 6px 14px rgb(0 0 0 / 0.07))',
      ':hover':
        'var(--generated-button-hover-shadow, inset 0 1px 0 rgb(255 255 255 / 0.3), inset 0 -1px 0 rgb(0 0 0 / 0.08), 0 2px 0 rgb(0 0 0 / 0.12), 0 9px 18px rgb(0 0 0 / 0.1))',
      ':active':
        'var(--generated-button-active-shadow, inset 0 2px 5px rgb(0 0 0 / 0.14), 0 1px 2px rgb(0 0 0 / 0.12))',
    },
    fontFamily: 'var(--generated-button-font, inherit)',
    fontWeight: 700,
    letterSpacing: 'var(--generated-button-letter-spacing, normal)',
    minHeight: 'var(--generated-button-min-height, 42px)',
    opacity: { ':disabled': 0.42 },
    paddingBlock: 'var(--generated-button-padding-block, 1px)',
    paddingInline: 18,
    textTransform: 'var(--generated-button-text-transform, none)',
    transform: {
      default: 'translateY(0)',
      ':hover': 'var(--generated-button-hover-transform, translateY(-1px))',
      ':active': 'var(--generated-button-active-transform, translateY(1px))',
    },
    transition: 'var(--generated-button-transition, box-shadow 150ms ease, transform 150ms ease)',
  },
  primaryButton: {
    backgroundColor: 'var(--control-accent)',
    backgroundImage:
      'var(--generated-primary-button-background, linear-gradient(180deg, rgb(255 255 255 / 0.18), transparent 36%))',
    borderColor: 'var(--control-accent)',
    boxShadow: {
      default:
        'var(--generated-primary-button-shadow, inset 0 1px 0 rgb(255 255 255 / 0.34), inset 0 -1px 0 rgb(0 0 0 / 0.14), 0 2px 0 color-mix(in srgb, var(--control-accent) 38%, #000), 0 7px 16px color-mix(in srgb, var(--control-accent) 14%, transparent))',
      ':hover':
        'var(--generated-primary-button-hover-shadow, inset 0 1px 0 rgb(255 255 255 / 0.42), inset 0 -1px 0 rgb(0 0 0 / 0.14), 0 3px 0 color-mix(in srgb, var(--control-accent) 42%, #000), 0 9px 18px color-mix(in srgb, var(--control-accent) 18%, transparent))',
      ':active':
        'var(--generated-primary-button-active-shadow, inset 0 2px 5px rgb(0 0 0 / 0.2), 0 1px 0 color-mix(in srgb, var(--control-accent) 38%, #000))',
    },
    color: 'var(--control-accent-contrast)',
    fontWeight: 800,
  },
  dangerButton: {
    backgroundColor: 'var(--control-surface-strong)',
    backgroundImage:
      'var(--generated-danger-button-background, linear-gradient(180deg, color-mix(in srgb, var(--control-danger) 10%, transparent), transparent))',
    borderColor: 'var(--control-danger)',
    color: 'var(--control-danger)',
  },
  iconButton: {
    alignItems: 'center',
    backdropFilter: 'var(--control-interactive-backdrop-filter, none)',
    backgroundColor: 'var(--control-surface-strong)',
    backgroundImage:
      'var(--generated-button-background, radial-gradient(circle at 35% 20%, rgb(255 255 255 / 0.22), transparent 46%))',
    borderColor: 'var(--control-border)',
    borderRadius: 'var(--generated-icon-radius, calc(var(--control-radius) * 0.75))',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default:
        'var(--generated-button-shadow, inset 0 1px 0 rgb(255 255 255 / 0.3), 0 3px 8px rgb(0 0 0 / 0.12))',
      ':hover':
        'var(--generated-button-hover-shadow, inset 0 1px 0 rgb(255 255 255 / 0.3), 0 9px 18px rgb(0 0 0 / 0.1))',
      ':active':
        'var(--generated-button-active-shadow, inset 0 2px 5px rgb(0 0 0 / 0.14), 0 1px 2px rgb(0 0 0 / 0.12))',
    },
    display: 'inline-flex',
    height: 42,
    justifyContent: 'center',
    transform: {
      default: 'translateY(0)',
      ':hover': 'var(--generated-button-hover-transform, translateY(-1px))',
      ':active': 'var(--generated-button-active-transform, translateY(1px))',
    },
    transition: 'var(--generated-button-transition, box-shadow 150ms ease, transform 150ms ease)',
    width: 42,
  },
  icon: { height: 18, stroke: 'currentColor', strokeLinecap: 'round', strokeWidth: 2, width: 18 },
  segmented: {
    backgroundColor: 'rgb(0 0 0 / 0.07)',
    borderColor: 'var(--control-border)',
    borderRadius: 'var(--control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: 'var(--generated-segment-housing-shadow, none)',
    display: 'grid',
    gap: 'var(--generated-segment-gap, 0px)',
    gridTemplateColumns: 'repeat(3, 1fr)',
    padding: 'var(--generated-segment-padding, 4px)',
  },
  segmentedButton: {
    backgroundColor: 'var(--generated-segment-background-color, transparent)',
    backgroundImage: 'var(--generated-segment-background, none)',
    borderColor: 'var(--control-border)',
    borderStyle: 'solid',
    borderWidth: 'var(--generated-segment-border-width, 0px)',
    borderRadius: 'var(--generated-segment-radius, calc(var(--control-radius) - 2px))',
    boxShadow: 'var(--generated-segment-shadow, none)',
    color: 'var(--generated-segment-color, inherit)',
    fontFamily: 'var(--generated-button-font, inherit)',
    fontWeight: 'var(--generated-segment-weight, inherit)',
    letterSpacing: 'var(--generated-button-letter-spacing, normal)',
    minHeight: 'var(--generated-segment-min-height, 38px)',
    paddingInline: 10,
    textTransform: 'var(--generated-button-text-transform, none)',
    transform: {
      ':active': 'var(--generated-segment-press-transform, translateY(1px))',
    },
    transition: 'var(--generated-button-transition, box-shadow 150ms ease, transform 150ms ease)',
  },
  segmentedActive: {
    backgroundColor: 'var(--generated-segment-active-background, var(--control-surface-strong))',
    borderColor: 'var(--generated-segment-active-border, var(--control-border))',
    boxShadow: 'var(--generated-segment-active-shadow, 0 3px 12px rgb(0 0 0 / 0.12))',
    color: 'var(--generated-segment-active-color, inherit)',
    fontWeight: 'var(--generated-segment-active-weight, 800)',
    transform: 'var(--generated-segment-active-transform, translateY(0))',
  },
  switchRow: { alignItems: 'center', display: 'flex', gap: 16 },
  switch: {
    backgroundColor: 'rgb(0 0 0 / 0.16)',
    borderColor: 'var(--control-border)',
    borderRadius: 999,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: 'var(--generated-switch-housing-shadow, none)',
    height: 32,
    padding: 3,
    transition: 'background 160ms ease',
    width: 58,
  },
  switchActive: { backgroundColor: 'var(--control-positive)' },
  switchThumb: {
    backgroundColor: 'var(--control-surface-strong)',
    borderRadius: '50%',
    boxShadow: 'var(--generated-switch-thumb-shadow, 0 2px 8px rgb(0 0 0 / 0.25))',
    display: 'block',
    height: 24,
    transition: 'transform 160ms ease',
    width: 24,
  },
  switchThumbActive: { transform: 'translateX(25px)' },
  stackBlock: { display: 'block' },
  mutedSmall: { color: 'var(--control-muted)', display: 'block', marginTop: 4 },
  form: { padding: 'clamp(22px, 4vw, 48px)' },
  fieldGrid: {
    display: 'grid',
    gap: '28px 18px',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    '@media (max-width: 980px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '@media (max-width: 680px)': { gridTemplateColumns: '1fr' },
  },
  field: { display: 'grid', gap: 9 },
  fieldLabel: {
    alignItems: 'center',
    display: 'flex',
    fontFamily: 'var(--generated-field-label-font, inherit)',
    fontSize: '0.7rem',
    fontWeight: 800,
    justifyContent: 'space-between',
    letterSpacing: '0.09em',
    textTransform: 'uppercase',
  },
  fieldHelp: { color: 'var(--control-muted)', fontSize: '0.72rem' },
  input: {
    backgroundColor: 'var(--control-surface-strong)',
    backgroundImage: 'var(--generated-input-background, none)',
    borderColor: 'var(--control-border)',
    borderRadius: 'var(--control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default: 'var(--generated-input-shadow, none)',
      ':focus': 'var(--generated-input-focus-shadow, none)',
    },
    color: 'inherit',
    minHeight: 46,
    outline: { ':focus-visible': '2px solid var(--control-accent)' },
    outlineOffset: { ':focus-visible': 3 },
    padding: '11px 13px',
    transition: 'box-shadow 160ms ease, transform 160ms ease',
    width: '100%',
  },
  textarea: { minHeight: 118, resize: 'vertical' },
  fieldWide: {
    gridColumn: 'span 3',
    '@media (max-width: 980px)': { gridColumn: 'span 2' },
    '@media (max-width: 680px)': { gridColumn: 'auto' },
  },
  range: { accentColor: 'var(--control-accent)', width: '100%' },
  kineticRangeControl: {
    borderRadius: 'calc(var(--control-radius) + 4px)',
    height: 42,
    outline: { ':focus-within': '2px solid var(--control-accent)' },
    outlineOffset: { ':focus-within': 3 },
    position: 'relative',
  },
  kineticRangeValue: (value: string) => ({ '--catalog-range-value': value }),
  kineticRangeInput: {
    appearance: 'none',
    cursor: 'pointer',
    height: '100%',
    inset: 0,
    margin: 0,
    opacity: 0,
    position: 'absolute',
    width: '100%',
    zIndex: 2,
  },
  kineticRangeRail: {
    backgroundColor: 'color-mix(in srgb, var(--kinetic-background) 78%, var(--kinetic-foreground))',
    borderColor: 'var(--control-border)',
    borderRadius: 999,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 1px 2px 3px color-mix(in srgb, var(--kinetic-foreground) 28%, transparent), inset -1px -1px 0 color-mix(in srgb, white 22%, transparent)',
    height: 6,
    left: 9,
    overflow: 'visible',
    position: 'absolute',
    right: 9,
    top: 18,
  },
  kineticRangeFill: {
    backgroundColor: 'var(--kinetic-accent)',
    borderRadius: 999,
    display: 'block',
    height: '100%',
    width: 'var(--catalog-range-value)',
  },
  kineticRangeKnob: {
    backgroundColor: 'color-mix(in srgb, var(--kinetic-background) 92%, white)',
    borderColor: 'var(--kinetic-foreground)',
    borderRadius: 'max(2px, calc(var(--kinetic-radius) * 0.4))',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 1px 1px 0 color-mix(in srgb, white 48%, transparent), inset -1px -1px 0 var(--kinetic-edge-shadow), 1px 2px 0 color-mix(in srgb, var(--kinetic-foreground) 28%, transparent), 2px 4px 7px color-mix(in srgb, var(--kinetic-foreground) 13%, transparent)',
    display: 'block',
    height: 24,
    left: 'var(--catalog-range-value)',
    position: 'absolute',
    top: '50%',
    transform: 'translate(-50%, -50%)',
    transition: 'left 90ms linear',
    width: 18,
  },
  kineticRangeKnobMark: {
    backgroundColor: 'color-mix(in srgb, var(--kinetic-foreground) 32%, transparent)',
    display: 'block',
    height: 10,
    left: 'calc(50% - 1px)',
    position: 'absolute',
    top: 6,
    width: 2,
  },
  choiceGrid: {
    alignItems: 'start',
    borderTopColor: 'var(--control-border)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'grid',
    gap: 28,
    gridTemplateColumns: '1fr 1fr 2fr',
    marginTop: 42,
    paddingTop: 36,
    '@media (max-width: 980px)': { gridTemplateColumns: '1fr 1fr' },
    '@media (max-width: 680px)': { gridTemplateColumns: '1fr' },
  },
  choiceGroup: { borderWidth: 0, display: 'grid', gap: 14, margin: 0, padding: 0 },
  choiceLegend: {
    fontFamily: 'var(--generated-field-label-font, inherit)',
    fontSize: '0.7rem',
    fontWeight: 800,
    letterSpacing: '0.09em',
    marginBottom: 17,
    textTransform: 'uppercase',
  },
  choiceLabel: { alignItems: 'center', display: 'flex', gap: 10 },
  choiceInput: { accentColor: 'var(--control-accent)', height: 18, width: 18 },
  kineticChoiceInput: {
    appearance: 'none',
    backgroundColor: {
      default: 'color-mix(in srgb, var(--kinetic-background) 92%, white)',
      ':checked': 'var(--kinetic-accent)',
    },
    borderColor: 'var(--kinetic-foreground)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default:
        'inset 1px 1px 0 color-mix(in srgb, white 54%, transparent), inset -1px -1px 0 var(--kinetic-edge-shadow), min(2px, var(--kinetic-shadow-x)) 3px 0 color-mix(in srgb, var(--kinetic-foreground) 30%, transparent)',
      ':checked':
        'inset 1px 1px 0 color-mix(in srgb, white 46%, transparent), inset -1px -1px 0 var(--kinetic-edge-shadow), min(2px, var(--kinetic-shadow-x)) 3px 0 color-mix(in srgb, var(--kinetic-accent) 52%, var(--kinetic-foreground))',
    },
    cursor: 'pointer',
    opacity: { ':disabled': 0.4 },
    outline: { ':focus-visible': '2px solid var(--kinetic-accent)' },
    outlineOffset: { ':focus-visible': 3 },
    transform: {
      ':active': 'translate(var(--kinetic-control-press-x), var(--kinetic-control-press))',
    },
    transition: 'var(--generated-button-transition)',
  },
  kineticCheckbox: {
    backgroundImage: {
      default: 'none',
      ':checked':
        'linear-gradient(135deg, transparent 38%, var(--kinetic-background) 39% 55%, transparent 56%)',
    },
    borderRadius: 'max(2px, calc(var(--control-radius) * 0.35))',
  },
  kineticRadio: {
    backgroundImage: {
      default: 'none',
      ':checked': 'radial-gradient(circle, var(--kinetic-background) 0 27%, transparent 30%)',
    },
    borderRadius: '50%',
  },
  pickerGroup: {
    alignItems: 'start',
    alignSelf: 'start',
    display: 'grid',
    gap: 16,
    gridTemplateColumns: '0.7fr 1fr 1.8fr',
    '@media (max-width: 980px)': { gridColumn: 'span 2' },
    '@media (max-width: 680px)': { gridColumn: 'auto', gridTemplateColumns: '1fr' },
  },
  colorInput: {
    backgroundColor: 'var(--control-surface-strong)',
    backgroundImage: 'var(--generated-input-background, none)',
    borderColor: 'var(--control-border)',
    borderRadius: 'var(--control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default: 'var(--generated-input-shadow, none)',
      ':focus': 'var(--generated-input-focus-shadow, none)',
    },
    height: 46,
    outline: { ':focus-visible': '2px solid var(--control-accent)' },
    outlineOffset: { ':focus-visible': 3 },
    padding: 4,
    width: '100%',
  },
  fileInput: {
    alignSelf: 'start',
    color: 'var(--control-muted)',
    fontSize: '0.72rem',
    maxWidth: '100%',
    outline: { ':focus-visible': '2px solid var(--control-accent)' },
    outlineOffset: { ':focus-visible': 3 },
  },
  badge: {
    borderColor: 'var(--control-border)',
    borderRadius: 999,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'inline-flex',
    fontSize: '0.65rem',
    fontWeight: 900,
    letterSpacing: '0.09em',
    padding: '6px 10px',
    textTransform: 'uppercase',
  },
  badgePositive: { borderColor: 'var(--control-positive)', color: 'var(--control-positive)' },
  badgeWarning: { borderColor: 'var(--control-warning)', color: 'var(--control-warning)' },
  badgeDanger: { borderColor: 'var(--control-danger)', color: 'var(--control-danger)' },
  badgeSolid: {
    backgroundColor: 'var(--control-accent)',
    borderColor: 'var(--control-accent)',
    color: 'var(--control-accent-contrast)',
  },
  badgeBoard: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    overflow: 'hidden',
    '@media (max-width: 980px)': { gridTemplateColumns: '1fr' },
  },
  badgeBoardItem: {
    borderRightColor: 'var(--control-border)',
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    minHeight: 190,
    padding: 26,
    '@media (max-width: 980px)': {
      borderBottomColor: 'var(--control-border)',
      borderBottomStyle: 'solid',
      borderBottomWidth: 1,
      borderRightWidth: 0,
    },
  },
  badgeBoardLabel: {
    display: 'block',
    fontSize: '0.68rem',
    fontWeight: 900,
    letterSpacing: '0.1em',
    marginBottom: 70,
    textTransform: 'uppercase',
  },
  countBadge: {
    alignItems: 'center',
    backgroundColor: 'var(--control-accent)',
    borderColor: 'var(--control-accent)',
    borderRadius: 999,
    borderStyle: 'solid',
    borderWidth: 1,
    color: 'var(--control-accent-contrast)',
    display: 'inline-flex',
    fontSize: '0.68rem',
    fontWeight: 900,
    height: 30,
    justifyContent: 'center',
    minWidth: 30,
    paddingInline: 8,
  },
  cardGrid: {
    display: 'grid',
    gap: 16,
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    '@media (max-width: 980px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '@media (max-width: 680px)': { gridTemplateColumns: '1fr' },
  },
  card: { padding: 26 },
  cardTitle: {
    display: 'block',
    fontFamily: 'var(--guide-display, inherit)',
    fontSize: '2rem',
    fontWeight: 500,
    marginBlock: '65px 12px',
  },
  cardCopy: { color: 'var(--control-muted)', lineHeight: 1.55 },
  meter: { backgroundColor: 'rgb(0 0 0 / 0.1)', height: 4, marginBlock: 24, overflow: 'hidden' },
  meterValue: {
    backgroundColor: 'var(--control-accent)',
    display: 'block',
    height: '100%',
    width: '72%',
  },
  textAction: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    fontSize: '0.72rem',
    fontWeight: 900,
    letterSpacing: '0.09em',
    padding: 0,
    textTransform: 'uppercase',
  },
  tallCard: { display: 'flex', flexDirection: 'column', minHeight: 390 },
  cardEyebrow: {
    fontSize: '0.68rem',
    fontWeight: 900,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  metric: {
    display: 'block',
    fontFamily: 'var(--guide-display, inherit)',
    fontSize: 'clamp(4rem, 7vw, 7rem)',
    fontWeight: 500,
    letterSpacing: '-0.07em',
    lineHeight: 0.8,
    marginBlock: 'auto 18px',
  },
  actionTitle: {
    display: 'block',
    fontFamily: 'var(--guide-display, inherit)',
    fontSize: 'clamp(2.1rem, 3.5vw, 3.6rem)',
    fontWeight: 500,
    letterSpacing: '-0.045em',
    lineHeight: 1,
    marginBlock: '70px 16px',
  },
  actionButton: { alignSelf: 'flex-start', marginTop: 'auto' },
  sparkline: {
    alignItems: 'end',
    display: 'grid',
    gap: 5,
    gridTemplateColumns: 'repeat(7, 1fr)',
    height: 58,
    marginTop: 24,
  },
  sparkBar: (height: string) => ({
    backgroundColor: 'var(--control-accent)',
    display: 'block',
    height,
  }),
  feedbackGrid: { display: 'grid', gap: 14 },
  feedbackCard: {
    alignItems: 'flex-start',
    display: 'grid',
    gap: 16,
    gridTemplateColumns: 'auto 1fr auto',
    padding: 24,
  },
  feedbackPositive: { borderColor: 'var(--control-positive)' },
  feedbackWarning: { borderColor: 'var(--control-warning)' },
  feedbackMark: {
    alignItems: 'center',
    backgroundColor: 'var(--control-accent)',
    borderRadius: '50%',
    color: 'var(--control-accent-contrast)',
    display: 'inline-flex',
    fontFamily: 'Georgia, serif',
    fontStyle: 'italic',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  feedbackMarkPositive: {
    backgroundColor: 'var(--control-positive)',
    fontFamily: 'inherit',
    fontStyle: 'normal',
  },
  feedbackMarkWarning: {
    backgroundColor: 'var(--control-warning)',
    fontFamily: 'inherit',
    fontStyle: 'normal',
  },
  feedbackCopy: {
    color: 'var(--control-muted)',
    fontSize: '0.86rem',
    lineHeight: 1.55,
    marginBottom: 0,
  },
  dismiss: { backgroundColor: 'transparent', borderWidth: 0, fontSize: '1.35rem' },
  listGrid: {
    display: 'grid',
    gap: 16,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    '@media (max-width: 680px)': { gridTemplateColumns: '1fr' },
  },
  list: { listStyle: 'none', marginBlock: '28px 0', padding: 0 },
  listItem: {
    alignItems: 'center',
    borderTopColor: 'var(--control-border)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'grid',
    gap: 16,
    gridTemplateColumns: '28px 1fr',
    paddingBlock: 16,
  },
  listIndex: {
    color: 'var(--control-muted)',
    fontFamily: 'var(--guide-mono, monospace)',
    fontSize: '0.68rem',
  },
  listIndexActive: { color: 'var(--control-accent)' },
  listTitleComplete: {
    textDecoration: 'line-through',
    textDecorationColor: 'var(--control-positive)',
  },
  navigationItem: {
    borderTopColor: 'var(--control-border)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  navigationButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    color: 'inherit',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'space-between',
    minHeight: 72,
    paddingInline: 12,
    textAlign: 'left',
    width: '100%',
  },
  navigationActive: {
    backgroundColor: 'color-mix(in srgb, var(--control-accent) 12%, transparent)',
    boxShadow: 'inset 3px 0 0 var(--control-accent)',
  },
  tableShell: { marginTop: 16, overflowX: 'auto' },
  tableHeading: { minWidth: 760, padding: '22px 24px' },
  tableHeadingTitle: {
    display: 'block',
    fontFamily: 'var(--guide-display, inherit)',
    fontSize: '1.35rem',
    marginTop: 5,
  },
  table: { borderCollapse: 'collapse', minWidth: 760, width: '100%' },
  tableCell: {
    borderTopColor: 'var(--control-border)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    padding: '17px 24px',
    textAlign: 'left',
  },
  tableHead: {
    color: 'var(--control-muted)',
    fontSize: '0.66rem',
    letterSpacing: '0.09em',
    textTransform: 'uppercase',
  },
  tableRowHead: { fontFamily: 'var(--guide-display, inherit)' },
  tableRow: {
    backgroundColor: { ':hover': 'color-mix(in srgb, var(--control-accent) 7%, transparent)' },
  },
  denseTable: { marginTop: 16 },
  denseTableRow: {
    backgroundColor: {
      default: 'transparent',
      ':hover': 'color-mix(in srgb, var(--kinetic-accent) 8%, var(--kinetic-background))',
    },
    transition: 'background-color 140ms ease',
  },
  denseIdentity: { alignItems: 'flex-start', display: 'flex', gap: 13 },
  denseOrdinal: {
    alignItems: 'center',
    backgroundColor: 'var(--kinetic-foreground)',
    color: 'var(--kinetic-background)',
    display: 'inline-flex',
    flex: '0 0 auto',
    fontFamily: 'var(--guide-mono, ui-monospace, monospace)',
    fontSize: '0.65rem',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  denseStack: { display: 'grid', gap: 5, minWidth: 0 },
  denseMeta: {
    color: 'color-mix(in srgb, var(--kinetic-foreground) 58%, transparent)',
    fontFamily: 'var(--guide-mono, ui-monospace, monospace)',
    fontSize: '0.63rem',
    fontWeight: 500,
    letterSpacing: '0.045em',
    overflowWrap: 'anywhere',
    textTransform: 'uppercase',
  },
  denseReason: { lineHeight: 1.45, margin: 0 },
  denseState: {
    borderColor: 'currentColor',
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'inline-flex',
    fontSize: '0.64rem',
    fontWeight: 900,
    letterSpacing: '0.08em',
    padding: '5px 7px',
    textTransform: 'uppercase',
  },
  denseStateReady: {
    backgroundColor: 'var(--kinetic-foreground)',
    color: 'var(--kinetic-background)',
  },
  denseStateReview: { color: 'var(--kinetic-accent)' },
  composition: { overflow: 'hidden' },
  compositionHeader: {
    alignItems: 'center',
    borderBottomColor: 'var(--control-border)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    display: 'flex',
    justifyContent: 'space-between',
    minHeight: 94,
    padding: '20px 26px',
    '@media (max-width: 680px)': { alignItems: 'flex-start', flexDirection: 'column', gap: 18 },
  },
  compositionMeta: {
    color: 'var(--control-muted)',
    display: 'block',
    fontFamily: 'var(--guide-mono, monospace)',
    fontSize: '0.65rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  compositionHeaderTitle: {
    display: 'block',
    fontFamily: 'var(--guide-display, inherit)',
    fontSize: '1.5rem',
    marginTop: 5,
  },
  compositionActions: { alignItems: 'center', display: 'flex', gap: 12 },
  compositionBody: {
    display: 'grid',
    gridTemplateColumns: '210px minmax(0, 1fr)',
    minHeight: 640,
    '@media (max-width: 980px)': { gridTemplateColumns: '150px minmax(0, 1fr)' },
    '@media (max-width: 680px)': { display: 'block' },
  },
  compositionNav: {
    borderRightColor: 'var(--control-border)',
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
    padding: '30px 18px',
    '@media (max-width: 680px)': {
      borderBottomColor: 'var(--control-border)',
      borderBottomStyle: 'solid',
      borderBottomWidth: 1,
      borderRightWidth: 0,
      flexFlow: 'row wrap',
    },
  },
  compositionNavHeading: {
    marginBlock: '0 18px',
    marginInline: 12,
    '@media (max-width: 680px)': { flexBasis: '100%' },
  },
  compositionNavLink: {
    borderRadius: 'calc(var(--control-radius) / 2)',
    color: 'inherit',
    fontSize: '0.78rem',
    fontWeight: 700,
    padding: 12,
    textDecoration: 'none',
  },
  compositionNavActive: {
    backgroundColor: 'color-mix(in srgb, var(--control-accent) 14%, transparent)',
    color: 'var(--control-accent)',
  },
  compositionMain: { padding: 'clamp(24px, 4vw, 50px)' },
  compositionTitle: {
    alignItems: 'end',
    display: 'flex',
    justifyContent: 'space-between',
    '@media (max-width: 680px)': { alignItems: 'flex-start', flexDirection: 'column', gap: 18 },
  },
  compositionTitleStrong: {
    display: 'block',
    fontFamily: 'var(--guide-display, inherit)',
    fontSize: 'clamp(2.8rem, 5vw, 5.4rem)',
    fontWeight: 500,
    letterSpacing: '-0.06em',
    lineHeight: 0.85,
    marginTop: 14,
    textTransform: 'capitalize',
  },
  metrics: {
    display: 'grid',
    gap: 12,
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    marginBlock: '52px 16px',
    '@media (max-width: 980px)': { gridTemplateColumns: '1fr' },
  },
  metricCard: {
    backgroundColor: 'var(--control-surface-strong)',
    borderColor: 'var(--control-border)',
    borderRadius: 'var(--control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    minHeight: 170,
    padding: 22,
  },
  metricValue: {
    display: 'block',
    fontFamily: 'var(--guide-display, inherit)',
    fontSize: '3rem',
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 500,
    marginBlock: '30px 5px',
  },
  activity: {
    backgroundColor: 'var(--control-surface-strong)',
    borderColor: 'var(--control-border)',
    borderRadius: 'var(--control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    padding: '8px 22px',
  },
  activityHeader: {
    alignItems: 'center',
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    minHeight: 64,
  },
  activityRow: {
    alignItems: 'center',
    borderTopColor: 'var(--control-border)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'grid',
    gap: 14,
    gridTemplateColumns: 'auto 1fr auto',
    minHeight: 76,
    '@media (max-width: 680px)': {
      alignItems: 'start',
      gridTemplateColumns: 'auto 1fr',
      paddingBlock: 14,
    },
  },
  activityCopy: { display: 'block', margin: 0 },
})

const styleMap: Readonly<Record<string, ReadonlyArray<Readonly<Record<string, unknown>>>>> = {
  'control-catalog': [catalogStyles.root],
  'catalog-grid': [catalogStyles.grid],
  'catalog-grid-actions': [],
  'catalog-specimen': [catalogStyles.surface, catalogStyles.specimen],
  'catalog-specimen-wide': [catalogStyles.specimenWide],
  'catalog-control-row': [catalogStyles.controlRow],
  'catalog-button': [catalogStyles.interactive, catalogStyles.button],
  'catalog-button-primary': [catalogStyles.primaryButton],
  'catalog-button-danger': [catalogStyles.dangerButton],
  'catalog-icon-button': [catalogStyles.interactive, catalogStyles.iconButton],
  'catalog-segmented': [catalogStyles.segmented],
  'catalog-switch-row': [catalogStyles.switchRow],
  'catalog-switch': [catalogStyles.interactive, catalogStyles.switch],
  'catalog-form': [catalogStyles.surface, catalogStyles.form],
  'catalog-field-grid': [catalogStyles.fieldGrid],
  'catalog-field': [catalogStyles.field],
  'catalog-field-wide': [catalogStyles.fieldWide],
  'catalog-range-field': [],
  'catalog-choice-grid': [catalogStyles.choiceGrid],
  'catalog-choice-group': [catalogStyles.choiceGroup],
  'catalog-picker-group': [catalogStyles.pickerGroup],
  'catalog-badge-board': [catalogStyles.surface, catalogStyles.badgeBoard],
  'catalog-badge': [catalogStyles.badge],
  'catalog-badge-positive': [catalogStyles.badgePositive],
  'catalog-badge-warning': [catalogStyles.badgeWarning],
  'catalog-badge-danger': [catalogStyles.badgeDanger],
  'catalog-badge-solid': [catalogStyles.badgeSolid],
  'catalog-count-badge': [catalogStyles.countBadge],
  'catalog-card-grid': [catalogStyles.cardGrid],
  'catalog-object-card': [catalogStyles.surface, catalogStyles.card],
  'catalog-metric-card': [catalogStyles.surface, catalogStyles.card, catalogStyles.tallCard],
  'catalog-action-card': [catalogStyles.surface, catalogStyles.card, catalogStyles.tallCard],
  'catalog-card-meter': [catalogStyles.meter],
  'catalog-text-action': [catalogStyles.interactive, catalogStyles.textAction],
  'catalog-sparkline': [catalogStyles.sparkline],
  'catalog-table-shell': [catalogStyles.surface, catalogStyles.tableShell],
  'catalog-table-heading': [catalogStyles.rowHeader, catalogStyles.tableHeading],
  'catalog-table': [catalogStyles.table],
  'catalog-table-action': [catalogStyles.interactive, catalogStyles.textAction],
  'catalog-list-grid': [catalogStyles.listGrid],
  'catalog-list-card': [catalogStyles.surface, catalogStyles.card],
  'catalog-navigation-list': [],
  'catalog-feedback-grid': [catalogStyles.feedbackGrid],
  'catalog-feedback-card': [catalogStyles.surface, catalogStyles.feedbackCard],
  'catalog-feedback-positive': [catalogStyles.feedbackPositive],
  'catalog-feedback-warning': [catalogStyles.feedbackWarning],
  'catalog-feedback-mark': [catalogStyles.feedbackMark],
  'catalog-composition': [catalogStyles.surface, catalogStyles.composition],
  'catalog-composition-header': [catalogStyles.compositionHeader],
  'catalog-composition-actions': [catalogStyles.compositionActions],
  'catalog-composition-body': [catalogStyles.compositionBody],
  'catalog-composition-main': [catalogStyles.compositionMain],
  'catalog-composition-title': [catalogStyles.compositionTitle],
  'catalog-composition-metrics': [catalogStyles.metrics],
  'catalog-composition-activity': [catalogStyles.activity],
  'visually-hidden': [sharedStyles.visuallyHidden],
}

export function catalogClass(...names: readonly string[]) {
  return className(...names.flatMap((name) => styleMap[name] ?? []))
}
