import * as stylex from '@stylexjs/stylex'

export const foundationStyles = stylex.create({
  catalog: {
    display: 'contents',
  },
  typeRoleGrid: {
    display: 'grid',
    gap: 14,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    '@media (max-width: 680px)': { gridTemplateColumns: '1fr' },
  },
  surface: {
    backgroundColor: 'var(--control-surface)',
    borderColor: 'var(--control-border)',
    borderRadius: 'var(--control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: 'var(--control-shadow)',
  },
  typeRoleCard: {
    minHeight: 265,
    padding: 24,
  },
  typeRoleHeader: {
    alignItems: 'center',
    borderBottomColor: 'var(--control-border)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    display: 'flex',
    justifyContent: 'space-between',
    paddingBottom: 13,
  },
  metaLabel: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.62rem',
    fontWeight: 800,
    letterSpacing: '0.09em',
    textTransform: 'uppercase',
  },
  metaCode: {
    color: 'var(--guide-muted)',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.58rem',
  },
  typeRoleStrong: {
    display: 'block',
    marginBlock: '30px 18px',
  },
  typeRoleCopy: {
    color: 'var(--guide-muted)',
    lineHeight: 1.55,
    margin: 0,
    maxWidth: 430,
  },
  displayType: {
    fontFamily: 'var(--guide-display)',
    fontSize: '5.5rem',
    fontWeight: 'var(--guide-display-weight, 400)',
    letterSpacing: 'var(--guide-display-tracking, -0.08em)',
    lineHeight: 'var(--guide-display-leading, 0.8)',
  },
  readingType: {
    fontFamily: 'var(--guide-font)',
    fontSize: '1.55rem',
    fontWeight: 550,
    lineHeight: 1.2,
  },
  numericType: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '2rem',
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: '0.04em',
  },
  machineType: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '1.25rem',
    fontWeight: 500,
  },
  typeLadder: {
    borderBlockColor: 'var(--guide-line)',
    borderBlockStyle: 'solid',
    borderBlockWidth: 1,
    marginTop: 16,
  },
  typeLadderRow: {
    alignItems: 'baseline',
    borderBottomColor: 'var(--guide-line)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    display: 'grid',
    gap: 24,
    gridTemplateColumns: '120px 1fr',
    paddingBlock: 18,
  },
  ladderMeta: {
    color: 'var(--guide-muted)',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.6rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  ladderDisplay: {
    fontFamily: 'var(--guide-display)',
    fontSize: 'clamp(2.4rem, 5vw, 5.2rem)',
    fontWeight: 'var(--guide-landmark-weight, 400)',
    letterSpacing: 'var(--guide-landmark-tracking, -0.06em)',
    lineHeight: 'var(--guide-landmark-leading, normal)',
  },
  ladderH1: {
    fontFamily: 'var(--guide-display)',
    fontSize: 'clamp(1.8rem, 3vw, 3rem)',
    fontWeight: 500,
  },
  ladderH2: {
    fontSize: '1.35rem',
    fontWeight: 700,
  },
  ladderContent: {
    margin: 0,
  },
  colorGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(6, minmax(0, 1fr))',
    '@media (max-width: 980px)': { gridTemplateColumns: 'repeat(3, minmax(0, 1fr))' },
    '@media (max-width: 680px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
  },
  swatch: {
    borderColor: 'var(--guide-line)',
    borderStyle: 'solid',
    borderWidth: '1px 1px 1px 0',
    display: 'flex',
    flexDirection: 'column',
    minHeight: 260,
    padding: 18,
  },
  swatchField: { backgroundColor: 'var(--control-surface)', color: 'var(--guide-ink)' },
  swatchInk: { backgroundColor: 'var(--guide-ink)', color: 'var(--control-surface)' },
  swatchAccent: {
    backgroundColor: 'var(--control-accent)',
    color: 'var(--control-accent-contrast)',
  },
  swatchPositive: { backgroundColor: 'var(--control-positive)', color: '#fff' },
  swatchWarning: { backgroundColor: 'var(--control-warning)', color: '#171718' },
  swatchDanger: { backgroundColor: 'var(--control-danger)', color: '#fff' },
  swatchLabel: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.58rem',
    fontWeight: 800,
    letterSpacing: '0.09em',
    textTransform: 'uppercase',
  },
  swatchName: {
    fontFamily: 'var(--guide-display)',
    fontSize: '1.45rem',
    fontWeight: 500,
    marginTop: 'auto',
  },
  swatchCode: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.56rem',
    marginTop: 9,
    opacity: 0.68,
  },
  spacingGrid: {
    display: 'grid',
    gap: 12,
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    '@media (max-width: 980px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '@media (max-width: 680px)': { gridTemplateColumns: '1fr' },
  },
  spaceToken: {
    alignItems: 'end',
    display: 'flex',
    justifyContent: 'space-between',
    minHeight: 150,
    overflow: 'hidden',
    padding: 18,
  },
  spaceTokenCopy: { display: 'grid', gap: 4 },
  spaceLabel: {
    color: 'var(--guide-muted)',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.58rem',
    textTransform: 'uppercase',
  },
  spaceValue: { fontFamily: 'var(--guide-display)', fontSize: '1.4rem' },
  spaceRuler: (value: string) => ({
    backgroundColor: 'var(--control-accent)',
    display: 'block',
    height: value,
    opacity: 0.85,
    width: value,
  }),
  layoutBoard: { padding: 24 },
  columnGrid: {
    display: 'grid',
    gap: 8,
    gridTemplateColumns: 'repeat(12, 1fr)',
    minHeight: 170,
  },
  column: {
    alignItems: 'end',
    backgroundColor: 'color-mix(in srgb, var(--control-accent) 17%, transparent)',
    borderColor: 'color-mix(in srgb, var(--control-accent) 36%, transparent)',
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.52rem',
    justifyContent: 'center',
    paddingBottom: 8,
  },
  layoutExamples: {
    display: 'grid',
    gap: 8,
    gridTemplateColumns: '3fr 6fr 3fr',
    marginTop: 8,
    '@media (max-width: 680px)': { gridTemplateColumns: '1fr' },
  },
  layoutExample: {
    backgroundColor: 'var(--control-surface-strong)',
    borderColor: 'var(--control-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    minHeight: 120,
    padding: 16,
  },
  layoutExampleMeta: {
    color: 'var(--guide-muted)',
    display: 'block',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.55rem',
    marginBottom: 26,
    textTransform: 'uppercase',
  },
  layoutExampleTitle: { display: 'block', fontSize: '0.8rem' },
  layoutTokens: {
    borderTopColor: 'var(--guide-line)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    marginBlock: '28px 0',
  },
  layoutToken: {
    borderRightColor: 'var(--guide-line)',
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    padding: 14,
  },
  layoutTokenTerm: {
    color: 'var(--guide-muted)',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.55rem',
    textTransform: 'uppercase',
  },
  layoutTokenValue: { fontFamily: 'var(--guide-display)', fontSize: '1.2rem', margin: '8px 0 0' },
  iconGrid: {
    display: 'grid',
    gap: 12,
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    '@media (max-width: 680px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
  },
  iconSpecimen: {
    alignItems: 'center',
    display: 'grid',
    gap: 16,
    justifyItems: 'center',
    minHeight: 180,
    padding: 20,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: 'var(--control-surface-strong)',
    borderColor: 'var(--control-border)',
    borderRadius: 'var(--control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    color: 'var(--guide-ink)',
    cursor: 'pointer',
    display: 'grid',
    height: 64,
    placeItems: 'center',
    width: 64,
    outline: { ':focus-visible': '3px solid var(--control-accent)' },
    outlineOffset: { ':focus-visible': 3 },
  },
  icon: {
    height: 26,
    stroke: 'currentColor',
    strokeLinecap: 'round',
    strokeLinejoin: 'round',
    strokeWidth: 1.6,
    width: 26,
  },
  iconLabel: {
    color: 'var(--guide-muted)',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.58rem',
    textTransform: 'uppercase',
  },
})
