import * as stylex from '@stylexjs/stylex'

const recordPulse = stylex.keyframes({
  '0%, 100%': {
    boxShadow: '0 0 0 0 rgb(255 70 117 / 0.42), 0 0 18px rgb(255 63 114 / 0.42)',
  },
  '50%': {
    boxShadow: '0 0 0 9px rgb(255 70 117 / 0), 0 0 26px rgb(255 63 114 / 0.62)',
  },
})

interface LiquidMaterialVariables {
  readonly bezel: string | number
  readonly bezelInset: string | number
  readonly bezelStroke: string | number
  readonly blur: string | number
  readonly blurFeedback: string | number
  readonly causticAlpha: string | number
  readonly chroma: string | number
  readonly chromaNegative: string | number
  readonly controlBlur: string | number
  readonly controlFill: string | number
  readonly controlRadius: string | number
  readonly copySkew: string | number
  readonly copyX: string | number
  readonly copyY: string | number
  readonly depth: string | number
  readonly edgeAlpha: string | number
  readonly highlightAlpha: string | number
  readonly iorShift: string | number
  readonly iorShiftDiagonal: string | number
  readonly lensScale: string | number
  readonly mapBlur: string | number
  readonly opacity: string | number
  readonly panelRadius: string | number
  readonly profileScale: string | number
  readonly railHeight: string | number
  readonly shadowBlur: string | number
  readonly shadowY: string | number
  readonly shapeRadius: string | number
  readonly specular: string | number
  readonly specularAlpha: string | number
  readonly thumbHeight: string | number
  readonly thumbWidth: string | number
  readonly tint: string | number
  readonly tintB: string | number
  readonly tintG: string | number
  readonly tintR: string | number
}

export const liquidInteractionStyles = stylex.create({
  root: {
    color: 'var(--guide-ink)',
  },
  materialVariables: (values: LiquidMaterialVariables) => ({
    '--lab-bezel': values.bezel,
    '--lab-bezel-inset': values.bezelInset,
    '--lab-bezel-stroke': values.bezelStroke,
    '--lab-blur': values.blur,
    '--lab-blur-feedback': values.blurFeedback,
    '--lab-caustic-alpha': values.causticAlpha,
    '--lab-chroma': values.chroma,
    '--lab-chroma-negative': values.chromaNegative,
    '--lab-control-blur': values.controlBlur,
    '--lab-control-fill': values.controlFill,
    '--lab-control-radius': values.controlRadius,
    '--lab-copy-skew': values.copySkew,
    '--lab-copy-x': values.copyX,
    '--lab-copy-y': values.copyY,
    '--lab-depth': values.depth,
    '--lab-edge-alpha': values.edgeAlpha,
    '--lab-highlight-alpha': values.highlightAlpha,
    '--lab-ior-shift': values.iorShift,
    '--lab-ior-shift-diagonal': values.iorShiftDiagonal,
    '--lab-lens-scale': values.lensScale,
    '--lab-map-blur': values.mapBlur,
    '--lab-opacity': values.opacity,
    '--lab-panel-radius': values.panelRadius,
    '--lab-profile-scale': values.profileScale,
    '--lab-rail-height': values.railHeight,
    '--lab-shadow-blur': values.shadowBlur,
    '--lab-shadow-y': values.shadowY,
    '--lab-shape-radius': values.shapeRadius,
    '--lab-specular': values.specular,
    '--lab-specular-alpha': values.specularAlpha,
    '--lab-thumb-height': values.thumbHeight,
    '--lab-thumb-width': values.thumbWidth,
    '--lab-tint': values.tint,
    '--lab-tint-b': values.tintB,
    '--lab-tint-g': values.tintG,
    '--lab-tint-r': values.tintR,
  }),
  stage: {
    backgroundColor: '#080d24',
    borderColor: 'rgb(255 255 255 / 0.2)',
    borderRadius: 44,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: 'inset 0 1px 0 rgb(255 255 255 / 0.2), 0 36px 100px rgb(0 0 24 / 0.42)',
    display: 'grid',
    gridTemplateRows: 'auto 1fr auto',
    isolation: 'isolate',
    minHeight: 720,
    overflow: 'hidden',
    padding: 30,
    position: 'relative',
    '@media (max-width: 780px)': {
      borderRadius: 30,
      minHeight: 660,
      padding: 20,
    },
    '@media (max-width: 520px)': {
      minHeight: 600,
    },
  },
  formStage: {
    minHeight: 950,
    '@media (max-width: 780px)': { minHeight: 800 },
    '@media (max-width: 520px)': { minHeight: 700 },
  },
  backdrop: {
    backgroundImage:
      'radial-gradient(circle at 18% 20%, rgb(84 72 202 / 0.16), transparent 29%), radial-gradient(circle at 82% 72%, rgb(22 150 183 / 0.13), transparent 32%), linear-gradient(145deg, #0b1020, #0b1425 52%, #09111d)',
    inset: 0,
    overflow: 'hidden',
    position: 'absolute',
    zIndex: -2,
    '::after': {
      backgroundImage:
        'linear-gradient(to bottom, rgb(3 7 18 / 0.06), rgb(3 7 18 / 0.26)), radial-gradient(circle at 50% 52%, transparent 24%, rgb(2 5 15 / 0.28) 100%)',
      content: '""',
      inset: 0,
      position: 'absolute',
    },
  },
  formBackdrop: {
    backgroundImage:
      'radial-gradient(circle at 24% 48%, rgb(25 132 171 / 0.14), transparent 28%), radial-gradient(circle at 76% 34%, rgb(116 75 189 / 0.13), transparent 31%), linear-gradient(145deg, #0a1722, #0e1927 54%, #09151f)',
  },
  ribbon: {
    borderRadius: 999,
    display: 'block',
    filter: 'blur(38px) saturate(125%)',
    opacity: 0.26,
    position: 'absolute',
    transform: 'rotate(-2deg)',
  },
  ribbonA: {
    backgroundImage:
      'linear-gradient(90deg, rgb(104 78 255 / 0.12), #815eff 28%, #1ccfe0 62%, rgb(22 190 205 / 0.1))',
    height: 92,
    left: '7%',
    top: '48%',
    width: '86%',
  },
  formRibbonA: {
    backgroundImage: 'linear-gradient(90deg, transparent, #27c7d6 38%, #7365de 70%, transparent)',
    height: 72,
    left: '8%',
    opacity: 0.2,
    top: '52%',
    transform: 'rotate(-6deg)',
    width: '84%',
  },
  ribbonB: {
    backgroundImage: 'linear-gradient(180deg, #ff6c9c, #755eff 55%, transparent)',
    height: 430,
    opacity: 0.11,
    right: '18%',
    top: '16%',
    transform: 'rotate(10deg)',
    width: 86,
  },
  hidden: { display: 'none' },
  orb: {
    borderRadius: '50%',
    filter: 'blur(3px)',
    opacity: 0.24,
    position: 'absolute',
  },
  formOrb: { opacity: 0.12 },
  orbA: {
    backgroundImage: 'radial-gradient(circle, #ffb563, #ff5b9f 32%, transparent 69%)',
    height: 92,
    left: '14%',
    top: '39%',
    width: 92,
  },
  orbB: {
    backgroundImage: 'radial-gradient(circle, #5aefff, #3c63ff 34%, transparent 70%)',
    bottom: '22%',
    height: 112,
    right: '12%',
    width: 112,
  },
  backdropGrid: {
    backgroundImage:
      'linear-gradient(rgb(255 255 255 / 0.035) 1px, transparent 1px), linear-gradient(90deg, rgb(255 255 255 / 0.035) 1px, transparent 1px)',
    backgroundSize: '48px 48px',
    inset: 0,
    maskImage: 'radial-gradient(circle at 50% 52%, #000, transparent 68%)',
    position: 'absolute',
  },
  stageHeader: {
    alignItems: 'flex-start',
    color: '#fff',
    display: 'flex',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 5,
    '@media (max-width: 780px)': { gap: 15 },
  },
  stageEyebrow: {
    color: 'rgb(239 246 255 / 0.68)',
    display: 'block',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.63rem',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  stageTitle: {
    display: 'block',
    fontFamily: 'var(--guide-display)',
    fontSize: 'clamp(1.9rem, 3vw, 3.1rem)',
    fontWeight: 500,
    letterSpacing: '-0.045em',
    marginTop: 7,
    '@media (max-width: 520px)': { fontSize: '1.55rem' },
  },
  rendererChip: {
    alignItems: 'center',
    backdropFilter: 'blur(18px)',
    backgroundColor: 'rgb(8 13 36 / 0.3)',
    borderColor: 'rgb(255 255 255 / 0.24)',
    borderRadius: 999,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'inline-flex',
    fontSize: '0.66rem',
    fontWeight: 800,
    gap: 8,
    letterSpacing: '0.08em',
    padding: '9px 12px',
    textTransform: 'uppercase',
    '@media (max-width: 780px)': { padding: '8px 10px' },
    '@media (max-width: 520px)': {
      fontSize: 0,
      height: 34,
      justifyContent: 'center',
      width: 34,
    },
  },
  statusLight: {
    backgroundColor: '#78fbd3',
    borderRadius: '50%',
    boxShadow: '0 0 14px #62f5ce',
    display: 'block',
    height: 7,
    width: 7,
  },
  statusFallback: {
    backgroundColor: '#ffd174',
    boxShadow: '0 0 14px #ffc24d',
  },
  stageFooter: {
    alignItems: 'center',
    borderTopColor: 'rgb(255 255 255 / 0.2)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    color: 'rgb(239 246 255 / 0.7)',
    display: 'flex',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.62rem',
    justifyContent: 'space-between',
    letterSpacing: '0.08em',
    paddingTop: 18,
    position: 'relative',
    textTransform: 'uppercase',
    zIndex: 5,
    '@media (max-width: 780px)': {
      display: 'grid',
      gap: 7,
      gridTemplateColumns: '1fr auto',
    },
    '@media (max-width: 520px)': { fontSize: '0.55rem' },
  },
  footerSecondary: { '@media (max-width: 780px)': { display: 'none' } },
  footerLink: { color: '#fff', textDecoration: 'none' },
  canvas: {
    height: '100%',
    inset: 0,
    pointerEvents: 'none',
    position: 'absolute',
    width: '100%',
  },
  buttonRenderLayer: {
    alignSelf: 'center',
    height: 320,
    justifySelf: 'center',
    position: 'relative',
    width: 680,
    zIndex: 2,
    '@media (max-width: 780px)': { transform: 'scale(0.72)' },
    '@media (max-width: 520px)': { transform: 'scale(0.5)' },
  },
  buttonOverlay: {
    alignItems: 'center',
    color: '#fff',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    inset: 0,
    justifyContent: 'center',
    position: 'absolute',
  },
  buttonRow: {
    alignItems: 'center',
    display: 'flex',
    gap: 14,
    justifyContent: 'center',
    minHeight: 68,
  },
  command: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: 'min(var(--liquid-control-radius, 18px), 32px)',
    color: '#fff',
    cursor: 'pointer',
    display: 'flex',
    height: 68,
    justifyContent: 'center',
    padding: 0,
    position: 'relative',
    textShadow: '0 1px 12px rgb(0 0 20 / 0.45)',
    outline: { ':focus-visible': '3px solid var(--liquid-accent)' },
    outlineOffset: { ':focus-visible': 4 },
    '::before': {
      backgroundImage: 'linear-gradient(90deg, rgb(255 255 255 / 0.64), rgb(255 255 255 / 0.08))',
      content: '""',
      height: 1,
      left: 13,
      opacity: 0.42,
      pointerEvents: 'none',
      position: 'absolute',
      right: '48%',
      top: 4,
    },
    '::after': {
      backgroundImage: 'linear-gradient(90deg, transparent, rgb(101 207 241 / 0.25), transparent)',
      bottom: 0,
      content: '""',
      height: 1,
      left: 12,
      opacity: 0.65,
      pointerEvents: 'none',
      position: 'absolute',
      right: 12,
    },
  },
  fallbackGlass: {
    backdropFilter: 'blur(24px) saturate(145%)',
    backgroundImage:
      'linear-gradient(180deg, rgb(255 255 255 / 0.12), transparent 32%), linear-gradient(110deg, rgb(202 225 239 / 0.12), rgb(117 166 201 / 0.07))',
    borderColor: 'rgb(255 255 255 / 0.3)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 0 rgb(255 255 255 / 0.48), inset 0 -1px 0 rgb(7 15 38 / 0.38), 0 2px 0 rgb(2 8 25 / 0.26), 0 9px 20px rgb(0 0 24 / 0.2)',
    transition: 'box-shadow 150ms ease, transform 150ms ease',
    transform: { ':hover': 'translateY(-1px)', ':active': 'translateY(1px)' },
  },
  commandPrimary: {
    gap: 17,
    justifyContent: 'flex-start',
    padding: '0 20px',
    width: 244,
  },
  commandCopy: {
    display: 'grid',
    fontSize: '0.94rem',
    fontWeight: 800,
    gap: 3,
    textAlign: 'left',
  },
  commandMeta: {
    color: 'rgb(239 246 255 / 0.64)',
    fontSize: '0.56rem',
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  commandArrow: { height: 21, marginLeft: 'auto', width: 21 },
  commandIconSvg: {
    fill: 'none',
    height: 23,
    stroke: 'currentColor',
    strokeLinecap: 'round',
    strokeLinejoin: 'round',
    strokeWidth: 1.8,
    width: 23,
  },
  commandLight: {
    backgroundColor: 'var(--liquid-accent)',
    borderRadius: 2,
    boxShadow: '0 0 12px color-mix(in srgb, var(--liquid-accent) 48%, transparent)',
    height: 30,
    opacity: 0.9,
    width: 3,
  },
  commandCompact: {
    flexDirection: 'column',
    fontSize: '0.62rem',
    fontWeight: 800,
    gap: 6,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    width: 112,
  },
  commandIcon: { width: 76 },
  commandFavorite: { color: '#ff8ebd' },
  commandAdd: {
    gap: 10,
    overflow: 'hidden',
    transition: 'width 280ms cubic-bezier(0.2, 0.85, 0.2, 1)',
    width: 76,
    '@media (prefers-reduced-motion: reduce)': { transitionDuration: '0.01ms' },
  },
  commandAddOpen: { width: 172 },
  commandAddLabel: {
    fontSize: '0.75rem',
    fontWeight: 800,
    opacity: 0,
    overflow: 'hidden',
    transition: 'opacity 120ms ease 0ms, width 240ms ease',
    whiteSpace: 'nowrap',
    width: 0,
    '@media (prefers-reduced-motion: reduce)': { transitionDuration: '0.01ms' },
  },
  commandAddLabelOpen: { opacity: 1, transitionDelay: '110ms', width: 72 },
  layerControl: {
    borderWidth: 0,
    borderRadius: 20,
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    height: 68,
    margin: 0,
    padding: 6,
    position: 'relative',
    width: 650,
  },
  layerButton: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: 14,
    color: '#fff',
    cursor: 'pointer',
    display: 'grid',
    height: 56,
    padding: '10px 18px',
    position: 'relative',
    textAlign: 'left',
    width: 'auto',
    zIndex: 1,
    outline: { ':focus-visible': '3px solid var(--liquid-accent)' },
    outlineOffset: { ':focus-visible': 4 },
  },
  layerLabel: { fontSize: '0.78rem', fontWeight: 800 },
  layerMeta: {
    color: 'rgb(239 246 255 / 0.58)',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.56rem',
    textTransform: 'uppercase',
  },
  activeDot: {
    backgroundColor: 'var(--liquid-accent)',
    borderRadius: 999,
    boxShadow: '0 0 14px var(--liquid-accent)',
    height: 5,
    position: 'absolute',
    right: 16,
    top: 14,
    width: 5,
  },
  specialRow: {
    alignItems: 'center',
    display: 'flex',
    gap: 14,
    height: 58,
    justifyContent: 'center',
  },
  specialControl: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: 'min(var(--liquid-control-radius, 16px), 26px)',
    color: '#fff',
    height: 58,
    position: 'relative',
    textShadow: '0 1px 12px rgb(0 0 20 / 0.45)',
    outline: { ':focus-visible': '3px solid var(--liquid-accent)' },
    outlineOffset: { ':focus-visible': 4 },
  },
  holdButton: {
    alignItems: 'center',
    display: 'flex',
    gap: 12,
    overflow: 'hidden',
    padding: '0 17px',
    textAlign: 'left',
    width: 230,
  },
  holdProgress: {
    backgroundImage: 'linear-gradient(90deg, rgb(255 98 137 / 0.38), rgb(255 85 126 / 0.7))',
    borderRadius: 11,
    inset: 4,
    position: 'absolute',
    transform: 'scaleX(0)',
    transformOrigin: 'left',
    transition: 'transform 160ms ease',
    '@media (prefers-reduced-motion: reduce)': { transitionDuration: '0.01ms' },
  },
  holdProgressActive: {
    transform: 'scaleX(1)',
    transitionDuration: '900ms',
    transitionTimingFunction: 'linear',
  },
  holdProgressConfirmed: {
    backgroundColor: 'rgb(64 217 168 / 0.48)',
    backgroundImage: 'none',
    transform: 'scaleX(1)',
  },
  holdForeground: { position: 'relative', zIndex: 1 },
  holdIcon: {
    alignItems: 'center',
    borderColor: 'rgb(255 255 255 / 0.35)',
    borderRadius: 8,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    flex: '0 0 auto',
    fontSize: '1rem',
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  holdTitle: { display: 'block', fontSize: '0.73rem' },
  holdMeta: {
    color: 'rgb(239 246 255 / 0.58)',
    display: 'block',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.52rem',
    marginTop: 3,
    textTransform: 'uppercase',
  },
  recordButton: { alignItems: 'center', display: 'flex', justifyContent: 'center', width: 76 },
  recordIndicator: {
    backgroundColor: '#ff6d8f',
    borderColor: 'rgb(255 255 255 / 0.14)',
    borderRadius: '50%',
    borderStyle: 'solid',
    borderWidth: 5,
    boxShadow: '0 0 10px rgb(255 63 114 / 0.34)',
    height: 22,
    position: 'relative',
    width: 22,
    zIndex: 1,
  },
  recordActive: {
    animationName: recordPulse,
    animationDuration: '1.4s',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'ease-in-out',
    borderRadius: 5,
    transform: 'scale(0.76)',
    '@media (prefers-reduced-motion: reduce)': { animationName: 'none' },
  },
  stepper: {
    alignItems: 'center',
    display: 'grid',
    gridTemplateColumns: '58px 1fr 58px',
    margin: 0,
    overflow: 'hidden',
    padding: 0,
    width: 250,
  },
  stepperButton: {
    alignSelf: 'stretch',
    backgroundColor: { ':hover': 'rgb(255 255 255 / 0.09)' },
    borderWidth: 0,
    color: '#fff',
    fontSize: '1.3rem',
    opacity: { ':disabled': 0.3 },
    position: 'relative',
    transition: 'background 140ms ease',
    zIndex: 1,
    outline: { ':focus-visible': '3px solid var(--liquid-accent)' },
  },
  stepperLeft: {
    borderRightColor: 'rgb(255 255 255 / 0.16)',
    borderRightStyle: 'solid',
    borderRightWidth: 1,
  },
  stepperRight: {
    borderLeftColor: 'rgb(255 255 255 / 0.16)',
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
  },
  stepperValue: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
  },
  stepperMeta: {
    color: 'rgb(239 246 255 / 0.58)',
    fontSize: '0.54rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  stepperOutput: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '1.1rem',
    fontVariantNumeric: 'tabular-nums',
    marginLeft: 10,
  },
  formRenderLayer: {
    alignSelf: 'center',
    display: 'grid',
    gap: 18,
    gridTemplateColumns: 'minmax(0, 1fr) 470px',
    height: 720,
    justifySelf: 'center',
    position: 'relative',
    width: 'min(100%, 1050px)',
    zIndex: 3,
    '@media (max-width: 1080px)': { transform: 'scale(0.88)' },
    '@media (max-width: 780px)': { transform: 'scale(0.68)' },
    '@media (max-width: 520px)': { transform: 'scale(0.48)' },
  },
  materialPlayground: { display: 'grid', gap: 16, gridTemplateRows: '448px 256px', minWidth: 0 },
  specimen: {
    backgroundColor: '#060a18',
    borderColor: 'rgb(255 255 255 / 0.15)',
    borderRadius: 18,
    borderStyle: 'solid',
    borderWidth: 1,
    color: '#fff',
    isolation: 'isolate',
    overflow: 'hidden',
    position: 'relative',
  },
  specimenHeader: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    left: 17,
    pointerEvents: 'none',
    position: 'absolute',
    right: 17,
    top: 15,
    zIndex: 5,
  },
  specimenFooter: {
    alignItems: 'center',
    bottom: 14,
    display: 'flex',
    justifyContent: 'space-between',
    left: 17,
    pointerEvents: 'none',
    position: 'absolute',
    right: 17,
    zIndex: 5,
  },
  specimenMeta: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.52rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  specimenMetaStrong: { fontWeight: 850 },
  specimenMuted: { color: 'rgb(239 246 255 / 0.56)' },
  specimenSource: {
    backgroundImage:
      'linear-gradient(rgb(255 255 255 / 0.09) 1px, transparent 1px), linear-gradient(90deg, rgb(255 255 255 / 0.09) 1px, transparent 1px), repeating-linear-gradient(115deg, transparent 0 9px, rgb(255 255 255 / 0.045) 10px 11px), radial-gradient(circle at 16% 82%, #ff668d 0 7%, transparent 25%), radial-gradient(circle at 84% 18%, #4ddbe8 0 8%, transparent 27%), linear-gradient(135deg, #24235b, #101932 55%, #272044)',
    backgroundSize: '18px 18px, 18px 18px, auto, auto, auto, auto',
    inset: 0,
    overflow: 'hidden',
    padding: '66px 34px',
    position: 'relative',
    '::after': {
      backgroundImage:
        'repeating-linear-gradient(90deg, #ff6b9c 0 6px, #f8e46a 6px 12px, #52e4e8 12px 18px, rgb(255 255 255 / 0.08) 18px 24px)',
      borderColor: 'rgb(255 255 255 / 0.5)',
      borderStyle: 'solid',
      borderWidth: 1,
      bottom: 92,
      content: '""',
      height: 13,
      left: '32%',
      opacity: 0.8,
      position: 'absolute',
      transform: 'rotate(-4deg)',
      width: 210,
    },
  },
  sourceMeta: {
    color: 'rgb(255 255 255 / 0.62)',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.52rem',
    letterSpacing: '0.12em',
    position: 'absolute',
    textTransform: 'uppercase',
    top: 70,
  },
  sourceTitle: {
    color: 'rgb(255 255 255 / 0.86)',
    display: 'block',
    fontFamily: 'var(--guide-display)',
    fontSize: 'clamp(3.8rem, 6vw, 5.4rem)',
    fontWeight: 500,
    letterSpacing: '-0.08em',
    lineHeight: 0.69,
    marginTop: 48,
  },
  sourceCircle: {
    borderColor: 'rgb(255 255 255 / 0.55)',
    borderRadius: '50%',
    borderStyle: 'solid',
    borderWidth: 1,
    height: 140,
    position: 'absolute',
    right: -30,
    top: 100,
    width: 140,
  },
  sourceCircleSmall: { height: 92, right: 34, top: 264, width: 92 },
  mapSource: {
    backgroundColor: '#0a0d16',
    backgroundImage:
      'linear-gradient(rgb(255 255 255 / 0.035) 1px, transparent 1px), linear-gradient(90deg, rgb(255 255 255 / 0.035) 1px, transparent 1px)',
    backgroundSize: '18px 18px',
    inset: 0,
    position: 'absolute',
  },
  specimenCanvas: { height: '100%', inset: 0, position: 'absolute', width: '100%', zIndex: 3 },
  materialDisabled: { opacity: 0.1 },
  fallbackSpecimen: {
    backdropFilter: 'blur(var(--lab-blur)) saturate(145%)',
    backgroundColor: 'rgb(219 242 255 / 0.1)',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / 0.16), transparent 38%), var(--lab-tint)',
    borderColor: 'rgb(255 255 255 / 0.4)',
    borderRadius: 'var(--lab-shape-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 0 rgb(255 255 255 / var(--lab-specular-alpha)), var(--lab-chroma-negative) 0 var(--lab-chroma) rgb(86 224 255 / 0.24), var(--lab-chroma) 0 var(--lab-chroma) rgb(255 88 154 / 0.2), 0 var(--lab-shadow-y) var(--lab-shadow-blur) rgb(0 0 24 / 0.34)',
    height: 210,
    left: '50%',
    position: 'absolute',
    top: '50%',
    transform: 'translate(-50%, -50%) scale(var(--lab-lens-scale))',
    transition:
      'backdrop-filter 160ms ease, border-radius 260ms ease, box-shadow 220ms ease, transform 240ms ease',
    width: 310,
    zIndex: 3,
  },
  fallbackConcave: {
    boxShadow:
      'inset 0 0 calc(var(--lab-bezel) * 1.4) rgb(0 0 24 / 0.56), inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-specular-alpha) * 0.62)), 0 var(--lab-shadow-y) var(--lab-shadow-blur) rgb(0 0 24 / 0.24)',
  },
  fallbackMap: {
    backdropFilter: 'none',
    backgroundImage:
      'radial-gradient(ellipse at center, #808080 0 32%, #59a58e 48%, #b55a75 66%, #808080 78%)',
    borderWidth: 0,
    filter: 'blur(var(--lab-map-blur))',
    height: 116,
    width: 270,
  },
  fallbackMapConcave: {
    backgroundImage:
      'radial-gradient(ellipse at center, #808080 0 18%, #b55a75 36%, #59a58e 59%, #808080 82%)',
  },
  fallbackMapLip: {
    backgroundImage:
      'radial-gradient(ellipse at center, #808080 0 24%, #59a58e 31%, #b55a75 39%, #808080 48%, #59a58e 66%, #b55a75 74%, #808080 84%)',
  },
  fallbackCopy: {
    color: 'rgb(255 255 255 / 0.72)',
    display: 'block',
    filter: 'blur(var(--lab-blur-feedback))',
    fontFamily: 'var(--guide-display)',
    fontSize: '5.2rem',
    fontWeight: 500,
    left: -92,
    letterSpacing: '-0.08em',
    lineHeight: 0.69,
    mixBlendMode: 'screen',
    opacity: 'var(--lab-opacity)',
    position: 'absolute',
    textShadow:
      'var(--lab-chroma-negative) 0 calc(2px + var(--lab-chroma)) rgb(61 220 255 / 0.7), var(--lab-chroma) 0 calc(2px + var(--lab-chroma)) rgb(255 77 161 / 0.62)',
    top: -7,
    transform:
      'translate(var(--lab-copy-x), var(--lab-copy-y)) skewX(var(--lab-copy-skew)) scale(var(--lab-profile-scale))',
    transformOrigin: 'center',
    transition:
      'filter 180ms ease, opacity 180ms ease, text-shadow 180ms ease, transform 240ms ease',
    whiteSpace: 'nowrap',
  },
  fallbackInset: {
    borderRadius: 'max(2px, calc(var(--lab-shape-radius) - var(--lab-bezel-inset)))',
    inset: 'var(--lab-bezel-inset)',
    pointerEvents: 'none',
    position: 'absolute',
  },
  fallbackCaustic: {
    backgroundImage:
      'radial-gradient(circle at 24% 12%, rgb(255 255 255 / var(--lab-caustic-alpha)), transparent 25%), linear-gradient(132deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 42%)',
    boxShadow:
      'inset calc(var(--lab-ior-shift) * -1) var(--lab-ior-shift-diagonal) var(--lab-bezel) rgb(255 255 255 / calc(var(--lab-caustic-alpha) * 0.24)), inset var(--lab-ior-shift) calc(var(--lab-ior-shift-diagonal) * -1) var(--lab-bezel) rgb(0 0 24 / 0.3)',
    opacity: 'var(--lab-specular)',
    transition:
      'border-radius 260ms ease, box-shadow 220ms ease, inset 220ms ease, opacity 180ms ease',
  },
  fallbackCausticConcave: {
    backgroundImage:
      'radial-gradient(circle at 72% 78%, rgb(255 255 255 / var(--lab-caustic-alpha)), transparent 22%), radial-gradient(ellipse at center, transparent 42%, rgb(0 0 24 / 0.42) 100%)',
  },
  fallbackBezel: {
    borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderStyle: 'solid',
    borderWidth: 'var(--lab-bezel-stroke)',
    boxShadow:
      'inset 0 0 var(--lab-bezel) rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.3)), 0 0 calc(var(--lab-bezel) * 0.45) rgb(85 224 255 / calc(var(--lab-specular) * 0.18))',
    transition:
      'border-radius 260ms ease, border-width 220ms ease, box-shadow 220ms ease, inset 220ms ease',
  },
  fallbackBezelLip: {
    borderStyle: 'double',
    borderWidth: 'max(3px, calc(var(--lab-bezel-stroke) * 2))',
    boxShadow:
      'inset 0 0 calc(var(--lab-bezel) * 0.48) rgb(255 255 255 / var(--lab-highlight-alpha)), 0 0 calc(var(--lab-bezel) * 0.32) rgb(90 226 255 / calc(var(--lab-specular) * 0.2))',
  },
  opticsForm: {
    backdropFilter: 'blur(var(--lab-control-blur)) saturate(145%)',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / var(--lab-control-fill))',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 24%, rgb(0 0 20 / 0.14) 78%)',
    borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderRadius: 'var(--lab-panel-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 0 rgb(255 255 255 / var(--lab-highlight-alpha)), inset calc(var(--lab-ior-shift) * -0.22) 0 var(--lab-bezel) rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / 0.08), var(--lab-chroma-negative) 0 calc(16px + var(--lab-depth) * 0.18) rgb(80 223 255 / 0.1), var(--lab-chroma) 0 calc(16px + var(--lab-depth) * 0.18) rgb(255 86 171 / 0.08), 0 calc(var(--lab-depth) * 0.25) calc(24px + var(--lab-depth) * 0.55) rgb(0 0 24 / 0.3)',
    color: '#fff',
    display: 'grid',
    gridTemplateRows: 'auto auto auto minmax(0, 1fr) auto',
    height: 720,
    isolation: 'isolate',
    overflow: 'hidden',
    padding: 22,
    position: 'relative',
    textShadow: '0 1px 14px rgb(0 0 24 / 0.4)',
    transition: 'backdrop-filter 220ms ease, border-radius 320ms ease, box-shadow 260ms ease',
    width: 470,
    '::before': {
      backgroundImage:
        'radial-gradient(circle at 9% 2%, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 24%), linear-gradient(105deg, transparent 35%, rgb(255 255 255 / 0.05) 48%, transparent 61%)',
      content: '""',
      inset: 0,
      pointerEvents: 'none',
      position: 'absolute',
      zIndex: 1,
    },
  },
  opticsDisabled: {
    backdropFilter: 'blur(1px) saturate(40%)',
    backgroundColor: 'rgb(8 13 29 / 0.78)',
    backgroundImage: 'none',
    boxShadow: 'inset 0 1px 0 rgb(255 255 255 / 0.12), 0 18px 40px rgb(0 0 24 / 0.26)',
  },
  controlCanvas: {
    inset: 0,
    pointerEvents: 'none',
    position: 'absolute',
    transition: 'opacity 220ms ease',
    zIndex: 0,
  },
  controlContent: { position: 'relative', zIndex: 2 },
  opticsHeader: {
    alignItems: 'center',
    borderBottomColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    display: 'flex',
    justifyContent: 'space-between',
    paddingBottom: 19,
    position: 'relative',
    zIndex: 2,
  },
  opticsEyebrow: {
    color: 'rgb(239 246 255 / 0.58)',
    display: 'block',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.58rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  opticsTitle: {
    display: 'block',
    fontFamily: 'var(--guide-display)',
    fontSize: '1.35rem',
    fontWeight: 500,
    marginTop: 3,
    textTransform: 'capitalize',
  },
  materialSwitch: {
    backdropFilter: 'blur(var(--lab-control-blur))',
    backgroundColor: 'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / 0.13)',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 48%)',
    borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderRadius: 999,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 2px rgb(0 0 20 / 0.34), 0 0 calc(5px + var(--lab-chroma)) rgb(98 225 255 / 0.12)',
    height: 30,
    padding: 3,
    transition: 'background 220ms ease, border-color 220ms ease, box-shadow 220ms ease',
    width: 54,
  },
  materialSwitchOn: {
    backgroundColor: 'rgb(53 217 174 / 0.48)',
    boxShadow:
      'inset 0 1px 3px rgb(0 44 45 / 0.38), 0 0 calc(10px + var(--lab-chroma)) rgb(67 236 204 / 0.25)',
  },
  materialSwitchThumb: {
    backgroundColor: 'var(--lab-tint)',
    backgroundImage: 'linear-gradient(145deg, rgb(255 255 255 / 0.9), rgb(255 255 255 / 0.34))',
    borderColor: 'rgb(255 255 255 / 0.76)',
    borderRadius: '50%',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 2px rgb(255 255 255 / 0.7), 0 2px calc(8px + var(--lab-depth) * 0.08) rgb(0 0 20 / 0.32)',
    boxSizing: 'border-box',
    display: 'block',
    height: 22,
    transform: 'translateX(0)',
    transition: 'background 220ms ease, box-shadow 220ms ease, transform 180ms ease',
    width: 22,
    '@media (prefers-reduced-motion: reduce)': { transitionDuration: '0.01ms' },
  },
  materialSwitchThumbOn: { transform: 'translateX(23px)' },
  formFields: {
    display: 'grid',
    gap: 12,
    gridTemplateColumns: '1.25fr 0.85fr 64px',
    padding: '14px 0',
    position: 'relative',
    zIndex: 2,
  },
  formField: { display: 'grid', gap: 7 },
  fieldLabel: {
    color: 'rgb(239 246 255 / 0.68)',
    fontSize: '0.61rem',
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  fieldControl: {
    backdropFilter: 'blur(var(--lab-control-blur)) saturate(140%)',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / var(--lab-control-fill))',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 43%)',
    borderColor: {
      default: 'rgb(255 255 255 / var(--lab-edge-alpha))',
      ':hover': 'rgb(255 255 255 / calc(var(--lab-edge-alpha) + 0.14))',
    },
    borderRadius: 'var(--lab-control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default:
        'inset 0 1px 0 rgb(255 255 255 / var(--lab-highlight-alpha)), inset 0 calc(var(--lab-depth) * -0.06) calc(8px + var(--lab-bezel) * 0.16) rgb(0 0 24 / 0.16), var(--lab-chroma-negative) 0 calc(4px + var(--lab-chroma)) rgb(78 222 255 / 0.07), var(--lab-chroma) 0 calc(4px + var(--lab-chroma)) rgb(255 91 176 / 0.06)',
      ':hover':
        'inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-highlight-alpha) + 0.1)), 0 5px calc(12px + var(--lab-depth) * 0.16) rgb(0 0 24 / 0.18)',
    },
    color: '#fff',
    minHeight: 38,
    padding: '0 12px',
    transition: 'backdrop-filter 220ms ease, border-radius 300ms ease, box-shadow 220ms ease',
    width: '100%',
    outline: { ':focus-visible': '3px solid var(--liquid-accent)' },
    outlineOffset: { ':focus-visible': 4 },
  },
  selectControl: { colorScheme: 'dark' },
  colorControl: { padding: 4 },
  rangeStack: {
    borderTopColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'grid',
    gap: '8px 10px',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    paddingTop: 14,
    position: 'relative',
    zIndex: 2,
  },
  rangeControl: {
    backdropFilter: 'blur(calc(var(--lab-control-blur) * 0.72))',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / calc(var(--lab-control-fill) * 0.72))',
    backgroundImage:
      'linear-gradient(135deg, rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.54)), transparent 52%)',
    borderColor: {
      default: 'rgb(255 255 255 / calc(var(--lab-edge-alpha) * 0.68))',
      ':hover': 'rgb(255 255 255 / var(--lab-edge-alpha))',
    },
    borderRadius: 'var(--lab-control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default:
        'inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.75)), inset 0 -5px calc(7px + var(--lab-bezel) * 0.1) rgb(0 0 24 / 0.1)',
      ':hover':
        'inset 0 1px 0 rgb(255 255 255 / var(--lab-highlight-alpha)), 0 4px calc(10px + var(--lab-depth) * 0.12) rgb(0 0 24 / 0.16)',
    },
    display: 'grid',
    gap: 6,
    padding: '8px 10px 7px',
    transform: { ':hover': 'translateY(-1px)' },
    transition:
      'backdrop-filter 220ms ease, border-radius 300ms ease, box-shadow 220ms ease, transform 160ms ease',
  },
  rangeHeader: {
    alignItems: 'center',
    color: 'rgb(239 246 255 / 0.68)',
    display: 'flex',
    fontSize: '0.54rem',
    fontWeight: 800,
    justifyContent: 'space-between',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  rangeOutput: {
    backgroundColor: 'rgb(255 255 255 / 0.08)',
    borderColor: 'rgb(255 255 255 / calc(var(--lab-edge-alpha) * 0.62))',
    borderRadius: 'calc(var(--lab-control-radius) * 0.55)',
    borderStyle: 'solid',
    borderWidth: 1,
    color: '#fff',
    fontFamily: 'var(--guide-mono)',
    fontVariantNumeric: 'tabular-nums',
    lineHeight: 1,
    padding: '3px 5px',
  },
  rangeInput: {
    appearance: 'none',
    backgroundColor: 'transparent',
    height: 18,
    margin: 0,
    width: '100%',
    '::-webkit-slider-runnable-track': {
      backgroundImage:
        'linear-gradient(90deg, rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / 0.78) 0 var(--range-position), rgb(255 255 255 / 0.13) var(--range-position) 100%)',
      borderColor: 'rgb(255 255 255 / calc(var(--lab-edge-alpha) * 0.72))',
      borderRadius: 'var(--lab-control-radius)',
      borderStyle: 'solid',
      borderWidth: 1,
      boxShadow:
        'inset 0 1px 3px rgb(0 0 20 / 0.34), var(--lab-chroma-negative) 0 calc(3px + var(--lab-chroma)) rgb(77 223 255 / 0.12), var(--lab-chroma) 0 calc(3px + var(--lab-chroma)) rgb(255 90 177 / 0.1)',
      height: 'var(--lab-rail-height)',
    },
    '::-webkit-slider-thumb': {
      appearance: 'none',
      backgroundColor: 'var(--lab-tint)',
      backgroundImage: 'linear-gradient(145deg, rgb(255 255 255 / 0.92), rgb(255 255 255 / 0.22))',
      borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
      borderRadius: 'calc(var(--lab-control-radius) * 0.62)',
      borderStyle: 'solid',
      borderWidth: 1,
      boxShadow:
        'inset 0 1px 2px rgb(255 255 255 / 0.75), var(--lab-chroma-negative) 0 calc(5px + var(--lab-chroma)) rgb(73 222 255 / 0.2), var(--lab-chroma) 0 calc(5px + var(--lab-chroma)) rgb(255 88 175 / 0.16), 0 calc(2px + var(--lab-depth) * 0.06) calc(7px + var(--lab-depth) * 0.14) rgb(0 0 20 / 0.32)',
      height: 'var(--lab-thumb-height)',
      marginTop: 'calc((var(--lab-rail-height) - var(--lab-thumb-height)) / 2 - 1px)',
      width: 'var(--lab-thumb-width)',
    },
    '::-moz-range-track': {
      backgroundImage:
        'linear-gradient(90deg, rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / 0.78) 0 var(--range-position), rgb(255 255 255 / 0.13) var(--range-position) 100%)',
      borderColor: 'rgb(255 255 255 / calc(var(--lab-edge-alpha) * 0.72))',
      borderRadius: 'var(--lab-control-radius)',
      borderStyle: 'solid',
      borderWidth: 1,
      height: 'var(--lab-rail-height)',
    },
    '::-moz-range-thumb': {
      backgroundColor: 'var(--lab-tint)',
      backgroundImage: 'linear-gradient(145deg, rgb(255 255 255 / 0.92), rgb(255 255 255 / 0.22))',
      borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
      borderRadius: 'calc(var(--lab-control-radius) * 0.62)',
      borderStyle: 'solid',
      borderWidth: 1,
      height: 'var(--lab-thumb-height)',
      width: 'var(--lab-thumb-width)',
    },
  },
  rangePosition: (position: string) => ({ '--range-position': position }),
  materialExport: {
    backdropFilter: 'blur(calc(var(--lab-control-blur) * 0.8))',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / calc(var(--lab-control-fill) * 0.75))',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.6)), transparent 40%)',
    borderColor: 'rgb(255 255 255 / calc(var(--lab-edge-alpha) * 0.72))',
    borderRadius: 'var(--lab-control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: 'inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.7))',
    marginTop: 11,
    minHeight: 0,
    overflow: 'hidden',
    position: 'relative',
    zIndex: 2,
  },
  exportHeader: {
    alignItems: 'center',
    borderBottomColor: 'rgb(255 255 255 / 0.13)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    display: 'flex',
    justifyContent: 'space-between',
    padding: '8px 11px',
  },
  exportMeta: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.5rem',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  exportMuted: { color: 'rgb(239 246 255 / 0.48)' },
  exportPre: {
    color: 'rgb(219 240 255 / 0.74)',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.56rem',
    height: 88,
    lineHeight: 1.5,
    margin: 0,
    overflow: 'auto',
    padding: '9px 11px',
    scrollbarColor: 'rgb(255 255 255 / 0.24) transparent',
  },
  opticsFooter: {
    alignItems: 'center',
    borderTopColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: 11,
    paddingTop: 11,
    position: 'relative',
    zIndex: 2,
  },
  exportStatus: {
    alignItems: 'center',
    color: 'rgb(239 246 255 / 0.72)',
    display: 'flex',
    fontSize: '0.65rem',
    gap: 8,
  },
  exportActions: { display: 'flex', gap: 7 },
  formButton: {
    backdropFilter: 'blur(var(--lab-control-blur))',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / calc(var(--lab-control-fill) + 0.03))',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 54%)',
    borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderRadius: 'var(--lab-control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default:
        'inset 0 1px 0 rgb(255 255 255 / var(--lab-highlight-alpha)), 0 calc(var(--lab-depth) * 0.08) calc(8px + var(--lab-depth) * 0.12) rgb(0 0 20 / 0.18)',
      ':hover':
        'inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-highlight-alpha) + 0.12)), 0 calc(var(--lab-depth) * 0.12) calc(10px + var(--lab-depth) * 0.16) rgb(0 0 20 / 0.24)',
      ':active': 'inset 0 2px calc(5px + var(--lab-depth) * 0.08) rgb(0 0 20 / 0.32)',
    },
    color: '#fff',
    fontSize: '0.6rem',
    fontWeight: 850,
    minHeight: 36,
    padding: '0 12px',
    textTransform: 'uppercase',
    transform: { ':hover': 'translateY(-1px)', ':active': 'translateY(1px)' },
    transition: 'border-radius 300ms ease, box-shadow 160ms ease, transform 160ms ease',
    outline: { ':focus-visible': '3px solid var(--liquid-accent)' },
    outlineOffset: { ':focus-visible': 4 },
  },
  formButtonPrimary: {
    backgroundColor: 'var(--lab-tint)',
    backgroundImage: 'linear-gradient(145deg, rgb(255 255 255 / 0.94), rgb(255 255 255 / 0.58))',
    borderColor: 'rgb(255 255 255 / 0.8)',
    color: '#11162d',
  },
})
