import * as stylex from '@stylexjs/stylex'

const recordPulse = stylex.keyframes({
  '0%, 100%': {
    boxShadow: '0 0 0 0 rgb(255 70 117 / 0.42), 0 0 18px rgb(255 63 114 / 0.42)',
  },
  '50%': {
    boxShadow: '0 0 0 9px rgb(255 70 117 / 0), 0 0 26px rgb(255 63 114 / 0.62)',
  },
})

interface LiquidMaterialVariables {
  readonly bezel: string | number
  readonly bezelInset: string | number
  readonly bezelStroke: string | number
  readonly blur: string | number
  readonly blurFeedback: string | number
  readonly causticAlpha: string | number
  readonly chroma: string | number
  readonly chromaNegative: string | number
  readonly controlBlur: string | number
  readonly controlFill: string | number
  readonly controlRadius: string | number
  readonly copySkew: string | number
  readonly copyX: string | number
  readonly copyY: string | number
  readonly depth: string | number
  readonly edgeAlpha: string | number
  readonly highlightAlpha: string | number
  readonly iorShift: string | number
  readonly iorShiftDiagonal: string | number
  readonly lensScale: string | number
  readonly mapBlur: string | number
  readonly opacity: string | number
  readonly panelRadius: string | number
  readonly profileScale: string | number
  readonly railHeight: string | number
  readonly shadowBlur: string | number
  readonly shadowY: string | number
  readonly shapeRadius: string | number
  readonly specular: string | number
  readonly specularAlpha: string | number
  readonly thumbHeight: string | number
  readonly thumbWidth: string | number
  readonly tint: string | number
  readonly tintB: string | number
  readonly tintG: string | number
  readonly tintR: string | number
}

interface FieldControlPosition {
  readonly height: string
  readonly radius: string
  readonly width: string
  readonly x: string
  readonly y: string
}

export const liquidInteractionStyles = stylex.create({
  root: {
    color: 'var(--guide-ink)',
  },
  materialVariables: (values: LiquidMaterialVariables) => ({
    '--lab-bezel': values.bezel,
    '--lab-bezel-inset': values.bezelInset,
    '--lab-bezel-stroke': values.bezelStroke,
    '--lab-blur': values.blur,
    '--lab-blur-feedback': values.blurFeedback,
    '--lab-caustic-alpha': values.causticAlpha,
    '--lab-chroma': values.chroma,
    '--lab-chroma-negative': values.chromaNegative,
    '--lab-control-blur': values.controlBlur,
    '--lab-control-fill': values.controlFill,
    '--lab-control-radius': values.controlRadius,
    '--lab-copy-skew': values.copySkew,
    '--lab-copy-x': values.copyX,
    '--lab-copy-y': values.copyY,
    '--lab-depth': values.depth,
    '--lab-edge-alpha': values.edgeAlpha,
    '--lab-highlight-alpha': values.highlightAlpha,
    '--lab-ior-shift': values.iorShift,
    '--lab-ior-shift-diagonal': values.iorShiftDiagonal,
    '--lab-lens-scale': values.lensScale,
    '--lab-map-blur': values.mapBlur,
    '--lab-opacity': values.opacity,
    '--lab-panel-radius': values.panelRadius,
    '--lab-profile-scale': values.profileScale,
    '--lab-rail-height': values.railHeight,
    '--lab-shadow-blur': values.shadowBlur,
    '--lab-shadow-y': values.shadowY,
    '--lab-shape-radius': values.shapeRadius,
    '--lab-specular': values.specular,
    '--lab-specular-alpha': values.specularAlpha,
    '--lab-thumb-height': values.thumbHeight,
    '--lab-thumb-width': values.thumbWidth,
    '--lab-tint': values.tint,
    '--lab-tint-b': values.tintB,
    '--lab-tint-g': values.tintG,
    '--lab-tint-r': values.tintR,
  }),
  stage: {
    backgroundColor: '#101019',
    borderColor: 'rgb(255 255 255 / 0.2)',
    borderRadius: 44,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: 'inset 0 1px 0 rgb(255 255 255 / 0.2), 0 36px 100px rgb(0 0 24 / 0.42)',
    display: 'grid',
    gridTemplateRows: 'auto 1fr auto',
    isolation: 'isolate',
    minHeight: 720,
    overflow: 'hidden',
    padding: 30,
    position: 'relative',
    '@media (max-width: 780px)': {
      borderRadius: 30,
      minHeight: 660,
      padding: 20,
    },
    '@media (max-width: 520px)': {
      minHeight: 600,
    },
  },
  formStage: {
    minHeight: 950,
    '@media (max-width: 780px)': { minHeight: 800 },
    '@media (max-width: 520px)': { minHeight: 700 },
  },
  backdrop: (values: { readonly washA: string; readonly washB: string }) => ({
    backgroundImage: `radial-gradient(circle at 22% 22%, ${values.washA}, transparent 42%), radial-gradient(circle at 78% 78%, ${values.washB}, transparent 44%), linear-gradient(160deg, #16161f, #1a1a24 55%, #121218)`,
    inset: 0,
    overflow: 'hidden',
    position: 'absolute',
    zIndex: -2,
    '::after': {
      backgroundImage:
        'linear-gradient(to bottom, rgb(3 7 18 / 0.04), rgb(3 7 18 / 0.18)), radial-gradient(circle at 50% 55%, transparent 32%, rgb(2 5 15 / 0.18) 100%)',
      content: '""',
      inset: 0,
      position: 'absolute',
    },
  }),
  stageHeader: {
    alignItems: 'flex-start',
    color: '#fff',
    display: 'flex',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 5,
    '@media (max-width: 780px)': { gap: 15 },
  },
  stageEyebrow: {
    color: 'rgb(239 246 255 / 0.68)',
    display: 'block',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.63rem',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  stageTitle: {
    display: 'block',
    fontFamily: 'var(--guide-display)',
    fontSize: 'clamp(1.9rem, 3vw, 3.1rem)',
    fontWeight: 500,
    letterSpacing: '-0.045em',
    marginTop: 7,
    '@media (max-width: 520px)': { fontSize: '1.55rem' },
  },
  rendererChip: {
    alignItems: 'center',
    backdropFilter: 'blur(18px)',
    backgroundColor: 'rgb(8 13 36 / 0.3)',
    borderColor: 'rgb(255 255 255 / 0.24)',
    borderRadius: 999,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'inline-flex',
    fontSize: '0.66rem',
    fontWeight: 800,
    gap: 8,
    letterSpacing: '0.08em',
    padding: '9px 12px',
    textTransform: 'uppercase',
    '@media (max-width: 780px)': { padding: '8px 10px' },
    '@media (max-width: 520px)': {
      fontSize: 0,
      height: 34,
      justifyContent: 'center',
      width: 34,
    },
  },
  statusLight: {
    backgroundColor: '#78fbd3',
    borderRadius: '50%',
    boxShadow: '0 0 14px #62f5ce',
    display: 'block',
    height: 7,
    width: 7,
  },
  statusFallback: {
    backgroundColor: '#ffd174',
    boxShadow: '0 0 14px #ffc24d',
  },
  stageFooter: {
    alignItems: 'center',
    borderTopColor: 'rgb(255 255 255 / 0.2)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    color: 'rgb(239 246 255 / 0.7)',
    display: 'flex',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.62rem',
    justifyContent: 'space-between',
    letterSpacing: '0.08em',
    paddingTop: 18,
    position: 'relative',
    textTransform: 'uppercase',
    zIndex: 5,
    '@media (max-width: 780px)': {
      display: 'grid',
      gap: 7,
      gridTemplateColumns: '1fr auto',
    },
    '@media (max-width: 520px)': { fontSize: '0.55rem' },
  },
  footerSecondary: { '@media (max-width: 780px)': { display: 'none' } },
  footerLink: { color: '#fff', textDecoration: 'none' },
  canvas: {
    height: '100%',
    inset: 0,
    pointerEvents: 'none',
    position: 'absolute',
    width: '100%',
  },
  buttonStage: {
    minHeight: 760,
    '@media (max-width: 780px)': { minHeight: 700 },
    '@media (max-width: 520px)': { minHeight: 620 },
  },
  buttonRenderLayer: {
    alignSelf: 'center',
    height: 474,
    justifySelf: 'center',
    position: 'relative',
    width: 800,
    zIndex: 2,
    '@media (max-width: 900px)': { transform: 'scale(0.82)' },
    '@media (max-width: 680px)': { transform: 'scale(0.63)' },
    '@media (max-width: 520px)': { transform: 'scale(0.47)' },
  },
  buttonFieldScene: {
    height: 474,
    isolation: 'isolate',
    position: 'relative',
    width: 800,
  },
  buttonOverlay: {
    color: '#fff',
    inset: 0,
    position: 'absolute',
    zIndex: 3,
  },
  fieldControlPosition: (values: FieldControlPosition) => ({
    '--control-height': values.height,
    '--control-radius': values.radius,
    '--control-width': values.width,
    '--control-x': values.x,
    '--control-y': values.y,
    borderRadius: 'var(--control-radius)',
    height: 'var(--control-height)',
    transform: 'translate(-50%, -50%) translate(var(--control-x), var(--control-y))',
    transitionDuration: '520ms',
    width: 'var(--control-width)',
  }),
  ferrousControl: {
    alignItems: 'center',
    backdropFilter: 'blur(calc(var(--lab-control-blur) * 0.7)) saturate(140%)',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / calc(var(--lab-control-fill) * 0.72))',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.72)), transparent 44%)',
    borderColor: 'rgb(255 255 255 / calc(var(--lab-edge-alpha) * 0.78))',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.88)), inset 0 -1px 0 rgb(4 10 30 / 0.32), 0 9px 24px rgb(0 0 24 / 0.2)',
    color: '#f8fbff',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    left: '50%',
    overflow: 'hidden',
    padding: 0,
    position: 'absolute',
    textShadow: '0 1px 14px rgb(0 0 20 / 0.56)',
    top: '50%',
    transformOrigin: 'center',
    transitionProperty: 'transform, width, height, border-radius, color',
    transitionTimingFunction: 'cubic-bezier(0.18, 0.82, 0.2, 1.14)',
    zIndex: 2,
    outline: { ':focus-visible': '3px solid var(--liquid-accent)' },
    outlineOffset: { ':focus-visible': 5 },
    '::before': {
      backgroundImage:
        'linear-gradient(104deg, rgb(255 255 255 / 0.62), rgb(255 255 255 / 0.08) 42%, transparent 64%)',
      content: '""',
      height: 1,
      left: 12,
      opacity: 0.34,
      pointerEvents: 'none',
      position: 'absolute',
      right: '42%',
      top: 4,
    },
    '::after': {
      backgroundImage: 'linear-gradient(90deg, transparent, rgb(105 217 255 / 0.28), transparent)',
      bottom: 1,
      content: '""',
      height: 1,
      left: 12,
      pointerEvents: 'none',
      position: 'absolute',
      right: 12,
    },
    '@media (prefers-reduced-motion: reduce)': { transitionDuration: '0.01ms' },
  },
  ferrousControlActive: {
    color: '#fff',
    zIndex: 5,
  },
  fieldFallbackGlass: {
    backdropFilter: 'blur(22px) saturate(145%)',
    backgroundColor: 'rgb(172 211 239 / 0.09)',
    backgroundImage:
      'linear-gradient(180deg, rgb(255 255 255 / 0.16), transparent 38%), linear-gradient(115deg, rgb(151 206 236 / 0.12), rgb(80 119 165 / 0.05))',
    borderColor: 'rgb(255 255 255 / 0.3)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 0 rgb(255 255 255 / 0.48), inset 0 -1px 0 rgb(7 15 38 / 0.42), 0 10px 26px rgb(0 0 24 / 0.28)',
  },
  fieldFavorite: { color: '#ff9ac5' },
  fieldCompactContent: {
    alignItems: 'center',
    display: 'flex',
    gap: 8,
    justifyContent: 'center',
    opacity: 1,
    paddingInline: 12,
    position: 'absolute',
    transition: 'opacity 90ms ease',
    whiteSpace: 'nowrap',
    zIndex: 2,
  },
  fieldCompactLabel: {
    fontSize: '0.6rem',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  fieldLayerSelector: {
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / calc(var(--lab-control-fill) * 0.92))',
    boxShadow:
      'inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.94)), inset 0 -1px 0 rgb(4 10 30 / 0.4), 0 12px 28px rgb(0 0 24 / 0.24)',
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    isolation: 'isolate',
    margin: 0,
    minInlineSize: 0,
    padding: 4,
  },
  fieldLayerOption: {
    alignItems: 'start',
    backgroundColor: 'transparent',
    borderRadius: 14,
    borderWidth: 0,
    color: 'rgb(238 247 255 / 0.58)',
    cursor: 'pointer',
    display: 'grid',
    gap: 2,
    height: '100%',
    justifyContent: 'start',
    padding: '7px 10px',
    position: 'relative',
    textAlign: 'left',
    textShadow: '0 1px 12px rgb(0 0 20 / 0.52)',
    zIndex: 2,
    outline: { ':focus-visible': '2px solid var(--liquid-accent)' },
    outlineOffset: { ':focus-visible': -3 },
  },
  fieldLayerOptionSelected: {
    backgroundColor: 'rgb(225 245 255 / 0.08)',
    color: '#fff',
  },
  fieldLayerOptionLabel: {
    fontSize: '0.58rem',
    fontWeight: 800,
    letterSpacing: '0.02em',
  },
  fieldLayerOptionMeta: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.42rem',
    letterSpacing: '0.04em',
    opacity: 0.62,
    textTransform: 'uppercase',
  },
  fieldLayerOptionDot: {
    backgroundColor: 'var(--liquid-accent)',
    borderRadius: '50%',
    boxShadow: '0 0 9px var(--liquid-accent)',
    height: 4,
    position: 'absolute',
    right: 8,
    top: 8,
    width: 4,
  },
  fieldActiveContent: {
    alignItems: 'center',
    display: 'flex',
    inset: 0,
    justifyContent: 'center',
    opacity: 1,
    position: 'absolute',
    transition: 'opacity 160ms ease 90ms',
    zIndex: 2,
  },
  fieldContentHidden: {
    opacity: 0,
    pointerEvents: 'none',
    transitionDelay: '0ms',
  },
  fieldPrimaryFace: {
    alignItems: 'center',
    display: 'grid',
    gap: 15,
    gridTemplateColumns: '3px minmax(0, 1fr) 21px',
    paddingInline: 20,
    width: '100%',
  },
  fieldCommandLight: {
    backgroundColor: 'var(--liquid-accent)',
    borderRadius: 2,
    boxShadow: '0 0 12px color-mix(in srgb, var(--liquid-accent) 48%, transparent)',
    height: 30,
    width: 3,
  },
  fieldFaceCopy: {
    display: 'grid',
    gap: 2,
    minWidth: 0,
    textAlign: 'left',
  },
  fieldFaceMeta: {
    color: 'rgb(232 245 255 / 0.56)',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.48rem',
    fontWeight: 700,
    letterSpacing: '0.07em',
    textTransform: 'uppercase',
  },
  fieldFaceTitle: {
    fontSize: '0.77rem',
    fontWeight: 800,
  },
  fieldStackFace: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
    justifyContent: 'center',
  },
  fieldStackLabel: {
    fontSize: '0.56rem',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  fieldIconFace: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },
  fieldInlineFace: {
    alignItems: 'center',
    display: 'flex',
    gap: 10,
    justifyContent: 'center',
    paddingInline: 18,
    whiteSpace: 'nowrap',
  },
  fieldInlineLabel: {
    fontSize: '0.7rem',
    fontWeight: 800,
  },
  fieldHoldFace: {
    alignItems: 'center',
    display: 'flex',
    gap: 12,
    paddingInline: 17,
    width: '100%',
  },
  fieldHoldIcon: {
    alignItems: 'center',
    borderColor: 'rgb(255 255 255 / 0.32)',
    borderRadius: 8,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    fontSize: '1rem',
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  fieldStepperFace: {
    alignItems: 'stretch',
    display: 'grid',
    gridTemplateColumns: '58px minmax(0, 1fr) 58px',
    height: '100%',
    width: '100%',
  },
  fieldStepperEdge: {
    alignItems: 'center',
    borderColor: 'rgb(255 255 255 / 0.13)',
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    display: 'flex',
    fontSize: '1.1rem',
    justifyContent: 'center',
  },
  fieldStepperValue: {
    alignItems: 'center',
    display: 'flex',
    gap: 9,
    justifyContent: 'center',
  },
  commandIconSvg: {
    fill: 'none',
    height: 21,
    stroke: 'currentColor',
    strokeLinecap: 'round',
    strokeLinejoin: 'round',
    strokeWidth: 1.8,
    width: 21,
  },
  fieldTextGlyph: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.8rem',
    fontWeight: 900,
  },
  fieldValueGlyph: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.72rem',
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 800,
  },
  fieldRecordIndicator: {
    backgroundColor: '#ff6d8f',
    borderColor: 'rgb(255 255 255 / 0.24)',
    borderRadius: '50%',
    borderStyle: 'solid',
    borderWidth: 4,
    boxShadow: '0 0 12px rgb(255 63 114 / 0.38)',
    height: 18,
    width: 18,
  },
  fieldRecordActive: {
    animationName: recordPulse,
    animationDuration: '1.4s',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'ease-in-out',
    borderRadius: 4,
    transform: 'scale(0.75)',
    '@media (prefers-reduced-motion: reduce)': { animationName: 'none' },
  },
  fieldHoldProgress: {
    backgroundImage: 'linear-gradient(90deg, rgb(255 98 137 / 0.18), rgb(255 85 126 / 0.55))',
    borderRadius: 'inherit',
    inset: 4,
    position: 'absolute',
    transform: 'scaleX(0)',
    transformOrigin: 'left',
    transition: 'transform 160ms ease',
  },
  fieldHoldProgressActive: {
    transform: 'scaleX(1)',
    transitionDuration: '900ms',
    transitionTimingFunction: 'linear',
  },
  fieldHoldProgressConfirmed: {
    backgroundColor: 'rgb(64 217 168 / 0.38)',
    backgroundImage: 'none',
    transform: 'scaleX(1)',
  },
  formRenderLayer: {
    alignSelf: 'center',
    display: 'grid',
    gap: 18,
    gridTemplateColumns: 'minmax(0, 1fr) 470px',
    height: 720,
    justifySelf: 'center',
    position: 'relative',
    width: 'min(100%, 1050px)',
    zIndex: 3,
    '@media (max-width: 1080px)': { transform: 'scale(0.88)' },
    '@media (max-width: 780px)': { transform: 'scale(0.68)' },
    '@media (max-width: 520px)': { transform: 'scale(0.48)' },
  },
  materialPlayground: { display: 'grid', gap: 16, gridTemplateRows: '448px 256px', minWidth: 0 },
  specimen: {
    backgroundColor: '#060a18',
    borderColor: 'rgb(255 255 255 / 0.15)',
    borderRadius: 18,
    borderStyle: 'solid',
    borderWidth: 1,
    color: '#fff',
    isolation: 'isolate',
    overflow: 'hidden',
    position: 'relative',
  },
  specimenHeader: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    left: 17,
    pointerEvents: 'none',
    position: 'absolute',
    right: 17,
    top: 15,
    zIndex: 5,
  },
  specimenFooter: {
    alignItems: 'center',
    bottom: 14,
    display: 'flex',
    justifyContent: 'space-between',
    left: 17,
    pointerEvents: 'none',
    position: 'absolute',
    right: 17,
    zIndex: 5,
  },
  specimenMeta: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.52rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  specimenMetaStrong: { fontWeight: 850 },
  specimenMuted: { color: 'rgb(239 246 255 / 0.56)' },
  specimenSource: {
    backgroundImage:
      'linear-gradient(rgb(255 255 255 / 0.09) 1px, transparent 1px), linear-gradient(90deg, rgb(255 255 255 / 0.09) 1px, transparent 1px), repeating-linear-gradient(115deg, transparent 0 9px, rgb(255 255 255 / 0.045) 10px 11px), radial-gradient(circle at 16% 82%, #ff668d 0 7%, transparent 25%), radial-gradient(circle at 84% 18%, #4ddbe8 0 8%, transparent 27%), linear-gradient(135deg, #24235b, #101932 55%, #272044)',
    backgroundSize: '18px 18px, 18px 18px, auto, auto, auto, auto',
    inset: 0,
    overflow: 'hidden',
    padding: '66px 34px',
    position: 'relative',
    '::after': {
      backgroundImage:
        'repeating-linear-gradient(90deg, #ff6b9c 0 6px, #f8e46a 6px 12px, #52e4e8 12px 18px, rgb(255 255 255 / 0.08) 18px 24px)',
      borderColor: 'rgb(255 255 255 / 0.5)',
      borderStyle: 'solid',
      borderWidth: 1,
      bottom: 92,
      content: '""',
      height: 13,
      left: '32%',
      opacity: 0.8,
      position: 'absolute',
      transform: 'rotate(-4deg)',
      width: 210,
    },
  },
  sourceMeta: {
    color: 'rgb(255 255 255 / 0.62)',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.52rem',
    letterSpacing: '0.12em',
    position: 'absolute',
    textTransform: 'uppercase',
    top: 70,
  },
  sourceTitle: {
    color: 'rgb(255 255 255 / 0.86)',
    display: 'block',
    fontFamily: 'var(--guide-display)',
    fontSize: 'clamp(3.8rem, 6vw, 5.4rem)',
    fontWeight: 500,
    letterSpacing: '-0.08em',
    lineHeight: 0.69,
    marginTop: 48,
  },
  sourceCircle: {
    borderColor: 'rgb(255 255 255 / 0.55)',
    borderRadius: '50%',
    borderStyle: 'solid',
    borderWidth: 1,
    height: 140,
    position: 'absolute',
    right: -30,
    top: 100,
    width: 140,
  },
  sourceCircleSmall: { height: 92, right: 34, top: 264, width: 92 },
  mapSource: {
    backgroundColor: '#0a0d16',
    backgroundImage:
      'linear-gradient(rgb(255 255 255 / 0.035) 1px, transparent 1px), linear-gradient(90deg, rgb(255 255 255 / 0.035) 1px, transparent 1px)',
    backgroundSize: '18px 18px',
    inset: 0,
    position: 'absolute',
  },
  specimenCanvas: { height: '100%', inset: 0, position: 'absolute', width: '100%', zIndex: 3 },
  materialDisabled: { opacity: 0.1 },
  fallbackSpecimen: {
    backdropFilter: 'blur(var(--lab-blur)) saturate(145%)',
    backgroundColor: 'rgb(219 242 255 / 0.1)',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / 0.16), transparent 38%), var(--lab-tint)',
    borderColor: 'rgb(255 255 255 / 0.4)',
    borderRadius: 'var(--lab-shape-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 0 rgb(255 255 255 / var(--lab-specular-alpha)), var(--lab-chroma-negative) 0 var(--lab-chroma) rgb(86 224 255 / 0.24), var(--lab-chroma) 0 var(--lab-chroma) rgb(255 88 154 / 0.2), 0 var(--lab-shadow-y) var(--lab-shadow-blur) rgb(0 0 24 / 0.34)',
    height: 210,
    left: '50%',
    position: 'absolute',
    top: '50%',
    transform: 'translate(-50%, -50%) scale(var(--lab-lens-scale))',
    transition:
      'backdrop-filter 160ms ease, border-radius 260ms ease, box-shadow 220ms ease, transform 240ms ease',
    width: 310,
    zIndex: 3,
  },
  fallbackConcave: {
    boxShadow:
      'inset 0 0 calc(var(--lab-bezel) * 1.4) rgb(0 0 24 / 0.56), inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-specular-alpha) * 0.62)), 0 var(--lab-shadow-y) var(--lab-shadow-blur) rgb(0 0 24 / 0.24)',
  },
  fallbackMap: {
    backdropFilter: 'none',
    backgroundImage:
      'radial-gradient(ellipse at center, #808080 0 32%, #59a58e 48%, #b55a75 66%, #808080 78%)',
    borderWidth: 0,
    filter: 'blur(var(--lab-map-blur))',
    height: 116,
    width: 270,
  },
  fallbackMapConcave: {
    backgroundImage:
      'radial-gradient(ellipse at center, #808080 0 18%, #b55a75 36%, #59a58e 59%, #808080 82%)',
  },
  fallbackMapLip: {
    backgroundImage:
      'radial-gradient(ellipse at center, #808080 0 24%, #59a58e 31%, #b55a75 39%, #808080 48%, #59a58e 66%, #b55a75 74%, #808080 84%)',
  },
  fallbackCopy: {
    color: 'rgb(255 255 255 / 0.72)',
    display: 'block',
    filter: 'blur(var(--lab-blur-feedback))',
    fontFamily: 'var(--guide-display)',
    fontSize: '5.2rem',
    fontWeight: 500,
    left: -92,
    letterSpacing: '-0.08em',
    lineHeight: 0.69,
    mixBlendMode: 'screen',
    opacity: 'var(--lab-opacity)',
    position: 'absolute',
    textShadow:
      'var(--lab-chroma-negative) 0 calc(2px + var(--lab-chroma)) rgb(61 220 255 / 0.7), var(--lab-chroma) 0 calc(2px + var(--lab-chroma)) rgb(255 77 161 / 0.62)',
    top: -7,
    transform:
      'translate(var(--lab-copy-x), var(--lab-copy-y)) skewX(var(--lab-copy-skew)) scale(var(--lab-profile-scale))',
    transformOrigin: 'center',
    transition:
      'filter 180ms ease, opacity 180ms ease, text-shadow 180ms ease, transform 240ms ease',
    whiteSpace: 'nowrap',
  },
  fallbackInset: {
    borderRadius: 'max(2px, calc(var(--lab-shape-radius) - var(--lab-bezel-inset)))',
    inset: 'var(--lab-bezel-inset)',
    pointerEvents: 'none',
    position: 'absolute',
  },
  fallbackCaustic: {
    backgroundImage:
      'radial-gradient(circle at 24% 12%, rgb(255 255 255 / var(--lab-caustic-alpha)), transparent 25%), linear-gradient(132deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 42%)',
    boxShadow:
      'inset calc(var(--lab-ior-shift) * -1) var(--lab-ior-shift-diagonal) var(--lab-bezel) rgb(255 255 255 / calc(var(--lab-caustic-alpha) * 0.24)), inset var(--lab-ior-shift) calc(var(--lab-ior-shift-diagonal) * -1) var(--lab-bezel) rgb(0 0 24 / 0.3)',
    opacity: 'var(--lab-specular)',
    transition:
      'border-radius 260ms ease, box-shadow 220ms ease, inset 220ms ease, opacity 180ms ease',
  },
  fallbackCausticConcave: {
    backgroundImage:
      'radial-gradient(circle at 72% 78%, rgb(255 255 255 / var(--lab-caustic-alpha)), transparent 22%), radial-gradient(ellipse at center, transparent 42%, rgb(0 0 24 / 0.42) 100%)',
  },
  fallbackBezel: {
    borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderStyle: 'solid',
    borderWidth: 'var(--lab-bezel-stroke)',
    boxShadow:
      'inset 0 0 var(--lab-bezel) rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.3)), 0 0 calc(var(--lab-bezel) * 0.45) rgb(85 224 255 / calc(var(--lab-specular) * 0.18))',
    transition:
      'border-radius 260ms ease, border-width 220ms ease, box-shadow 220ms ease, inset 220ms ease',
  },
  fallbackBezelLip: {
    borderStyle: 'double',
    borderWidth: 'max(3px, calc(var(--lab-bezel-stroke) * 2))',
    boxShadow:
      'inset 0 0 calc(var(--lab-bezel) * 0.48) rgb(255 255 255 / var(--lab-highlight-alpha)), 0 0 calc(var(--lab-bezel) * 0.32) rgb(90 226 255 / calc(var(--lab-specular) * 0.2))',
  },
  opticsForm: {
    backdropFilter: 'blur(var(--lab-control-blur)) saturate(145%)',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / var(--lab-control-fill))',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 24%, rgb(0 0 20 / 0.14) 78%)',
    borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderRadius: 'var(--lab-panel-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 0 rgb(255 255 255 / var(--lab-highlight-alpha)), inset calc(var(--lab-ior-shift) * -0.22) 0 var(--lab-bezel) rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / 0.08), var(--lab-chroma-negative) 0 calc(16px + var(--lab-depth) * 0.18) rgb(80 223 255 / 0.1), var(--lab-chroma) 0 calc(16px + var(--lab-depth) * 0.18) rgb(255 86 171 / 0.08), 0 calc(var(--lab-depth) * 0.25) calc(24px + var(--lab-depth) * 0.55) rgb(0 0 24 / 0.3)',
    color: '#fff',
    display: 'grid',
    gridTemplateRows: 'auto auto auto minmax(0, 1fr) auto',
    height: 720,
    isolation: 'isolate',
    overflow: 'hidden',
    padding: 22,
    position: 'relative',
    textShadow: '0 1px 14px rgb(0 0 24 / 0.4)',
    transition: 'backdrop-filter 220ms ease, border-radius 320ms ease, box-shadow 260ms ease',
    width: 470,
    '::before': {
      backgroundImage:
        'radial-gradient(circle at 9% 2%, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 24%), linear-gradient(105deg, transparent 35%, rgb(255 255 255 / 0.05) 48%, transparent 61%)',
      content: '""',
      inset: 0,
      pointerEvents: 'none',
      position: 'absolute',
      zIndex: 1,
    },
  },
  opticsDisabled: {
    backdropFilter: 'blur(1px) saturate(40%)',
    backgroundColor: 'rgb(8 13 29 / 0.78)',
    backgroundImage: 'none',
    boxShadow: 'inset 0 1px 0 rgb(255 255 255 / 0.12), 0 18px 40px rgb(0 0 24 / 0.26)',
  },
  controlCanvas: {
    inset: 0,
    pointerEvents: 'none',
    position: 'absolute',
    transition: 'opacity 220ms ease',
    zIndex: 0,
  },
  controlContent: { position: 'relative', zIndex: 2 },
  opticsHeader: {
    alignItems: 'center',
    borderBottomColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    display: 'flex',
    justifyContent: 'space-between',
    paddingBottom: 19,
    position: 'relative',
    zIndex: 2,
  },
  opticsEyebrow: {
    color: 'rgb(239 246 255 / 0.58)',
    display: 'block',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.58rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  opticsTitle: {
    display: 'block',
    fontFamily: 'var(--guide-display)',
    fontSize: '1.35rem',
    fontWeight: 500,
    marginTop: 3,
    textTransform: 'capitalize',
  },
  materialSwitch: {
    backdropFilter: 'blur(var(--lab-control-blur))',
    backgroundColor: 'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / 0.13)',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 48%)',
    borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderRadius: 999,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 2px rgb(0 0 20 / 0.34), 0 0 calc(5px + var(--lab-chroma)) rgb(98 225 255 / 0.12)',
    height: 30,
    padding: 3,
    transition: 'background 220ms ease, border-color 220ms ease, box-shadow 220ms ease',
    width: 54,
  },
  materialSwitchOn: {
    backgroundColor: 'rgb(53 217 174 / 0.48)',
    boxShadow:
      'inset 0 1px 3px rgb(0 44 45 / 0.38), 0 0 calc(10px + var(--lab-chroma)) rgb(67 236 204 / 0.25)',
  },
  materialSwitchThumb: {
    backgroundColor: 'var(--lab-tint)',
    backgroundImage: 'linear-gradient(145deg, rgb(255 255 255 / 0.9), rgb(255 255 255 / 0.34))',
    borderColor: 'rgb(255 255 255 / 0.76)',
    borderRadius: '50%',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 2px rgb(255 255 255 / 0.7), 0 2px calc(8px + var(--lab-depth) * 0.08) rgb(0 0 20 / 0.32)',
    boxSizing: 'border-box',
    display: 'block',
    height: 22,
    transform: 'translateX(0)',
    transition: 'background 220ms ease, box-shadow 220ms ease, transform 180ms ease',
    width: 22,
    '@media (prefers-reduced-motion: reduce)': { transitionDuration: '0.01ms' },
  },
  materialSwitchThumbOn: { transform: 'translateX(23px)' },
  formFields: {
    display: 'grid',
    gap: 12,
    gridTemplateColumns: '1.25fr 0.85fr 64px',
    padding: '14px 0',
    position: 'relative',
    zIndex: 2,
  },
  formField: { display: 'grid', gap: 7 },
  fieldLabel: {
    color: 'rgb(239 246 255 / 0.68)',
    fontSize: '0.61rem',
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  fieldControl: {
    backdropFilter: 'blur(var(--lab-control-blur)) saturate(140%)',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / var(--lab-control-fill))',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 43%)',
    borderColor: {
      default: 'rgb(255 255 255 / var(--lab-edge-alpha))',
      ':hover': 'rgb(255 255 255 / calc(var(--lab-edge-alpha) + 0.14))',
    },
    borderRadius: 'var(--lab-control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default:
        'inset 0 1px 0 rgb(255 255 255 / var(--lab-highlight-alpha)), inset 0 calc(var(--lab-depth) * -0.06) calc(8px + var(--lab-bezel) * 0.16) rgb(0 0 24 / 0.16), var(--lab-chroma-negative) 0 calc(4px + var(--lab-chroma)) rgb(78 222 255 / 0.07), var(--lab-chroma) 0 calc(4px + var(--lab-chroma)) rgb(255 91 176 / 0.06)',
      ':hover':
        'inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-highlight-alpha) + 0.1)), 0 5px calc(12px + var(--lab-depth) * 0.16) rgb(0 0 24 / 0.18)',
    },
    color: '#fff',
    minHeight: 38,
    padding: '0 12px',
    transition: 'backdrop-filter 220ms ease, border-radius 300ms ease, box-shadow 220ms ease',
    width: '100%',
    outline: { ':focus-visible': '3px solid var(--liquid-accent)' },
    outlineOffset: { ':focus-visible': 4 },
  },
  selectControl: { colorScheme: 'dark' },
  colorControl: { padding: 4 },
  rangeStack: {
    borderTopColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'grid',
    gap: '8px 10px',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    paddingTop: 14,
    position: 'relative',
    zIndex: 2,
  },
  rangeControl: {
    backdropFilter: 'blur(calc(var(--lab-control-blur) * 0.72))',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / calc(var(--lab-control-fill) * 0.72))',
    backgroundImage:
      'linear-gradient(135deg, rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.54)), transparent 52%)',
    borderColor: {
      default: 'rgb(255 255 255 / calc(var(--lab-edge-alpha) * 0.68))',
      ':hover': 'rgb(255 255 255 / var(--lab-edge-alpha))',
    },
    borderRadius: 'var(--lab-control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default:
        'inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.75)), inset 0 -5px calc(7px + var(--lab-bezel) * 0.1) rgb(0 0 24 / 0.1)',
      ':hover':
        'inset 0 1px 0 rgb(255 255 255 / var(--lab-highlight-alpha)), 0 4px calc(10px + var(--lab-depth) * 0.12) rgb(0 0 24 / 0.16)',
    },
    display: 'grid',
    gap: 6,
    padding: '8px 10px 7px',
    transform: { ':hover': 'translateY(-1px)' },
    transition:
      'backdrop-filter 220ms ease, border-radius 300ms ease, box-shadow 220ms ease, transform 160ms ease',
  },
  rangeHeader: {
    alignItems: 'center',
    color: 'rgb(239 246 255 / 0.68)',
    display: 'flex',
    fontSize: '0.54rem',
    fontWeight: 800,
    justifyContent: 'space-between',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  rangeOutput: {
    backgroundColor: 'rgb(255 255 255 / 0.08)',
    borderColor: 'rgb(255 255 255 / calc(var(--lab-edge-alpha) * 0.62))',
    borderRadius: 'calc(var(--lab-control-radius) * 0.55)',
    borderStyle: 'solid',
    borderWidth: 1,
    color: '#fff',
    fontFamily: 'var(--guide-mono)',
    fontVariantNumeric: 'tabular-nums',
    lineHeight: 1,
    padding: '3px 5px',
  },
  rangeInput: {
    appearance: 'none',
    backgroundColor: 'transparent',
    height: 18,
    margin: 0,
    width: '100%',
    '::-webkit-slider-runnable-track': {
      backgroundImage:
        'linear-gradient(90deg, rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / 0.78) 0 var(--range-position), rgb(255 255 255 / 0.13) var(--range-position) 100%)',
      borderColor: 'rgb(255 255 255 / calc(var(--lab-edge-alpha) * 0.72))',
      borderRadius: 'var(--lab-control-radius)',
      borderStyle: 'solid',
      borderWidth: 1,
      boxShadow:
        'inset 0 1px 3px rgb(0 0 20 / 0.34), var(--lab-chroma-negative) 0 calc(3px + var(--lab-chroma)) rgb(77 223 255 / 0.12), var(--lab-chroma) 0 calc(3px + var(--lab-chroma)) rgb(255 90 177 / 0.1)',
      height: 'var(--lab-rail-height)',
    },
    '::-webkit-slider-thumb': {
      appearance: 'none',
      backgroundColor: 'var(--lab-tint)',
      backgroundImage: 'linear-gradient(145deg, rgb(255 255 255 / 0.92), rgb(255 255 255 / 0.22))',
      borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
      borderRadius: 'calc(var(--lab-control-radius) * 0.62)',
      borderStyle: 'solid',
      borderWidth: 1,
      boxShadow:
        'inset 0 1px 2px rgb(255 255 255 / 0.75), var(--lab-chroma-negative) 0 calc(5px + var(--lab-chroma)) rgb(73 222 255 / 0.2), var(--lab-chroma) 0 calc(5px + var(--lab-chroma)) rgb(255 88 175 / 0.16), 0 calc(2px + var(--lab-depth) * 0.06) calc(7px + var(--lab-depth) * 0.14) rgb(0 0 20 / 0.32)',
      height: 'var(--lab-thumb-height)',
      marginTop: 'calc((var(--lab-rail-height) - var(--lab-thumb-height)) / 2 - 1px)',
      width: 'var(--lab-thumb-width)',
    },
    '::-moz-range-track': {
      backgroundImage:
        'linear-gradient(90deg, rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / 0.78) 0 var(--range-position), rgb(255 255 255 / 0.13) var(--range-position) 100%)',
      borderColor: 'rgb(255 255 255 / calc(var(--lab-edge-alpha) * 0.72))',
      borderRadius: 'var(--lab-control-radius)',
      borderStyle: 'solid',
      borderWidth: 1,
      height: 'var(--lab-rail-height)',
    },
    '::-moz-range-thumb': {
      backgroundColor: 'var(--lab-tint)',
      backgroundImage: 'linear-gradient(145deg, rgb(255 255 255 / 0.92), rgb(255 255 255 / 0.22))',
      borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
      borderRadius: 'calc(var(--lab-control-radius) * 0.62)',
      borderStyle: 'solid',
      borderWidth: 1,
      height: 'var(--lab-thumb-height)',
      width: 'var(--lab-thumb-width)',
    },
  },
  rangePosition: (position: string) => ({ '--range-position': position }),
  materialExport: {
    backdropFilter: 'blur(calc(var(--lab-control-blur) * 0.8))',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / calc(var(--lab-control-fill) * 0.75))',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.6)), transparent 40%)',
    borderColor: 'rgb(255 255 255 / calc(var(--lab-edge-alpha) * 0.72))',
    borderRadius: 'var(--lab-control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: 'inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-highlight-alpha) * 0.7))',
    marginTop: 11,
    minHeight: 0,
    overflow: 'hidden',
    position: 'relative',
    zIndex: 2,
  },
  exportHeader: {
    alignItems: 'center',
    borderBottomColor: 'rgb(255 255 255 / 0.13)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    display: 'flex',
    justifyContent: 'space-between',
    padding: '8px 11px',
  },
  exportMeta: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.5rem',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  exportMuted: { color: 'rgb(239 246 255 / 0.48)' },
  exportPre: {
    color: 'rgb(219 240 255 / 0.74)',
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.56rem',
    height: 88,
    lineHeight: 1.5,
    margin: 0,
    overflow: 'auto',
    padding: '9px 11px',
    scrollbarColor: 'rgb(255 255 255 / 0.24) transparent',
  },
  opticsFooter: {
    alignItems: 'center',
    borderTopColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: 11,
    paddingTop: 11,
    position: 'relative',
    zIndex: 2,
  },
  exportStatus: {
    alignItems: 'center',
    color: 'rgb(239 246 255 / 0.72)',
    display: 'flex',
    fontSize: '0.65rem',
    gap: 8,
  },
  exportActions: { display: 'flex', gap: 7 },
  formButton: {
    backdropFilter: 'blur(var(--lab-control-blur))',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / calc(var(--lab-control-fill) + 0.03))',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 54%)',
    borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderRadius: 'var(--lab-control-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default:
        'inset 0 1px 0 rgb(255 255 255 / var(--lab-highlight-alpha)), 0 calc(var(--lab-depth) * 0.08) calc(8px + var(--lab-depth) * 0.12) rgb(0 0 20 / 0.18)',
      ':hover':
        'inset 0 1px 0 rgb(255 255 255 / calc(var(--lab-highlight-alpha) + 0.12)), 0 calc(var(--lab-depth) * 0.12) calc(10px + var(--lab-depth) * 0.16) rgb(0 0 20 / 0.24)',
      ':active': 'inset 0 2px calc(5px + var(--lab-depth) * 0.08) rgb(0 0 20 / 0.32)',
    },
    color: '#fff',
    fontSize: '0.6rem',
    fontWeight: 850,
    minHeight: 36,
    padding: '0 12px',
    textTransform: 'uppercase',
    transform: { ':hover': 'translateY(-1px)', ':active': 'translateY(1px)' },
    transition: 'border-radius 300ms ease, box-shadow 160ms ease, transform 160ms ease',
    outline: { ':focus-visible': '3px solid var(--liquid-accent)' },
    outlineOffset: { ':focus-visible': 4 },
  },
  formButtonPrimary: {
    backgroundColor: 'var(--lab-tint)',
    backgroundImage: 'linear-gradient(145deg, rgb(255 255 255 / 0.94), rgb(255 255 255 / 0.58))',
    borderColor: 'rgb(255 255 255 / 0.8)',
    color: '#11162d',
  },
  formsPanel: {
    backdropFilter: 'blur(30px) saturate(150%)',
    backgroundColor:
      'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / calc(var(--lab-control-fill) + 0.05))',
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 32%)',
    borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderRadius: 'var(--lab-panel-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      'inset 0 1px 0 rgb(255 255 255 / var(--lab-highlight-alpha)), 0 20px 60px rgb(0 0 24 / 0.16)',
    color: '#fff',
    display: 'grid',
    gap: 36,
    padding: 'clamp(24px, 4vw, 44px)',
    position: 'relative',
    textShadow: '0 1px 14px rgb(0 0 24 / 0.3)',
  },
  choiceGrid: {
    alignItems: 'start',
    display: 'grid',
    gap: 24,
    gridTemplateColumns: '1fr 1fr 2fr',
    '@media (max-width: 780px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '@media (max-width: 480px)': { gridTemplateColumns: '1fr' },
  },
  choiceGroup: { borderWidth: 0, display: 'grid', gap: 14, margin: 0, padding: 0 },
  choiceLegend: {
    color: 'rgb(239 246 255 / 0.68)',
    fontSize: '0.61rem',
    fontWeight: 800,
    letterSpacing: '0.08em',
    marginBottom: 2,
    textTransform: 'uppercase',
  },
  choiceLabel: {
    alignItems: 'center',
    color: '#fff',
    display: 'flex',
    fontSize: '0.82rem',
    gap: 11,
  },
  choiceInput: {
    appearance: 'none',
    backdropFilter: 'blur(var(--lab-control-blur)) saturate(140%)',
    backgroundColor: {
      default:
        'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / var(--lab-control-fill))',
      ':checked':
        'rgb(var(--lab-tint-r) var(--lab-tint-g) var(--lab-tint-b) / calc(var(--lab-control-fill) + 0.42))',
    },
    backgroundImage:
      'linear-gradient(145deg, rgb(255 255 255 / var(--lab-highlight-alpha)), transparent 46%)',
    borderColor: 'rgb(255 255 255 / var(--lab-edge-alpha))',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: {
      default: 'inset 0 1px 0 rgb(255 255 255 / var(--lab-highlight-alpha))',
      ':checked':
        'inset 0 1px 0 rgb(255 255 255 / var(--lab-highlight-alpha)), 0 0 0 2px rgb(255 255 255 / 0.4)',
    },
    cursor: 'pointer',
    height: 20,
    outline: { ':focus-visible': '2px solid var(--liquid-accent)' },
    outlineOffset: { ':focus-visible': 3 },
    transition: 'background-color 180ms ease, box-shadow 180ms ease',
    width: 20,
  },
  choiceCheckbox: { borderRadius: 6 },
  choiceRadio: { borderRadius: '50%' },
  formsFieldGrid: {
    display: 'grid',
    gap: 24,
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    '@media (max-width: 820px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '@media (max-width: 480px)': { gridTemplateColumns: '1fr' },
  },
  formsFieldWide: {
    gridColumn: 'span 3',
    '@media (max-width: 820px)': { gridColumn: 'span 2' },
    '@media (max-width: 480px)': { gridColumn: 'span 1' },
  },
  formsFieldHelp: {
    color: 'rgb(239 246 255 / 0.5)',
    fontSize: '0.66rem',
  },
  formsTextarea: {
    minHeight: 96,
    padding: '10px 12px',
    resize: 'vertical',
  },
  formsPickerGroup: {
    display: 'grid',
    gap: 16,
    gridTemplateColumns: '0.6fr 0.9fr 1.5fr',
    '@media (max-width: 480px)': { gridTemplateColumns: '1fr' },
  },
  formsFileInput: {
    color: 'rgb(239 246 255 / 0.62)',
    fontSize: '0.72rem',
    maxWidth: '100%',
    outline: { ':focus-visible': '2px solid var(--liquid-accent)' },
    outlineOffset: { ':focus-visible': 3 },
  },
})
