import * as stylex from '@stylexjs/stylex'
import { className } from './shared.stylex'

export const workbenchStyles = stylex.create({
  root: {
    display: 'grid',
    gap: 24,
    gridTemplateColumns: 'minmax(0, 1.2fr) minmax(320px, 0.8fr)',
    marginTop: 32,
    '@media (max-width: 900px)': { gridTemplateColumns: '1fr' },
  },
  preview: {
    minHeight: 560,
    overflow: 'hidden',
    position: 'relative',
    transition:
      'background 180ms ease, border-radius 180ms ease, box-shadow 180ms ease, color 180ms ease',
    '@media (max-width: 900px)': { minHeight: 500 },
  },
  controls: {
    alignContent: 'start',
    backgroundColor: 'var(--control-surface-strong, #f4f1e9)',
    borderColor: 'var(--control-border, #26231e)',
    borderRadius: 'var(--control-radius, 0)',
    borderStyle: 'solid',
    borderWidth: 1,
    color: 'var(--generated-control-text, #24211c)',
    display: 'grid',
    minHeight: 560,
    padding: 22,
    '@media (max-width: 900px)': { minHeight: 500 },
  },
  row: { alignItems: 'center', display: 'flex', justifyContent: 'space-between' },
  controlsHeader: {
    borderBottomColor: 'var(--control-border)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingBottom: 15,
  },
  controlsFooter: {
    alignSelf: 'end',
    borderTopColor: 'var(--control-border)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    gap: 8,
    justifyContent: 'flex-end',
    marginTop: 16,
    paddingTop: 15,
    '@media (max-width: 560px)': { alignItems: 'stretch', flexDirection: 'column' },
  },
  meta: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.62rem',
    letterSpacing: '0.07em',
    textTransform: 'uppercase',
  },
  metaStrong: { fontWeight: 900 },
  muted: { color: 'var(--guide-muted)' },
  block: { display: 'block' },
  capitalize: { textTransform: 'capitalize' },
  fields: {
    display: 'grid',
    gap: '13px 16px',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    paddingBlock: 18,
    '@media (max-width: 560px)': { gridTemplateColumns: '1fr' },
  },
  field: { display: 'grid', gap: 7, minWidth: 0 },
  fieldLabel: { alignItems: 'center', display: 'flex', justifyContent: 'space-between' },
  fieldControl: {
    backgroundColor: 'transparent',
    borderColor: 'var(--control-border)',
    borderRadius: 0,
    borderStyle: 'solid',
    borderWidth: 1,
    color: 'inherit',
    minHeight: 35,
    paddingInline: 9,
    width: '100%',
  },
  colorControl: {
    backgroundColor: 'transparent',
    borderColor: 'var(--control-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    height: 35,
    padding: 3,
    width: '100%',
  },
  range: { accentColor: 'var(--control-accent)', marginBlock: 5, width: '100%' },
  toggle: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: 'var(--control-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    color: 'inherit',
    display: 'flex',
    justifyContent: 'space-between',
    minHeight: 35,
    paddingInline: 9,
  },
  details: {
    borderColor: 'var(--control-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    minHeight: 0,
  },
  summary: { cursor: 'pointer', fontWeight: 800, padding: 11 },
  pre: {
    borderTopColor: 'var(--control-border)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.58rem',
    height: 110,
    lineHeight: 1.5,
    margin: 0,
    overflow: 'auto',
    padding: 10,
  },
  footerButton: {
    backgroundColor: 'transparent',
    borderColor: 'var(--guide-ink)',
    borderRadius: 'var(--control-radius, 0)',
    borderStyle: 'solid',
    borderWidth: 1,
    color: 'inherit',
    fontSize: '0.62rem',
    fontWeight: 850,
    minHeight: 35,
    paddingInline: 12,
    textTransform: 'uppercase',
  },
  footerPrimary: {
    backgroundColor: 'var(--guide-ink)',
    color: 'var(--control-surface-strong, #fff)',
  },
  specimen: { maxWidth: 430, position: 'relative', textAlign: 'left', width: '100%' },
  specimenMeta: {
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.6rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  specimenTitle: {
    display: 'block',
    fontSize: 'clamp(2.7rem, 5vw, 5rem)',
    letterSpacing: '-0.06em',
    lineHeight: 0.9,
    marginBlock: 22,
  },
  specimenCopy: { lineHeight: 1.5, maxWidth: 310 },
  textureShapes: { display: 'flex', gap: 10, marginTop: 38 },
  textureShape: {
    borderColor: 'currentColor',
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'block',
    height: 34,
    width: 34,
  },
  textureCircle: { borderRadius: '50%' },
  textureDiamond: { transform: 'rotate(45deg) scale(0.72)' },
  printRule: {
    borderWidth: 0,
    borderTopColor: 'currentColor',
    borderTopStyle: 'solid',
    borderTopWidth: 3,
    marginBlock: '36px 12px',
  },
  signalPreview: { minHeight: 620, padding: 'clamp(20px, 4vw, 48px)' },
  signalSpecimen: { display: 'grid', gap: 18, textAlign: 'left', width: '100%' },
  specimenRow: { alignItems: 'center', display: 'flex', justifyContent: 'space-between' },
  signalInstruments: {
    display: 'grid',
    gap: 14,
    gridTemplateColumns: '1.35fr 0.65fr',
    '@media (max-width: 600px)': { gridTemplateColumns: '1fr' },
  },
  signalPlane: {
    borderColor: 'var(--guide-line)',
    borderStyle: 'solid',
    borderWidth: 1,
    minHeight: 300,
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
  },
  signalSpectrumPlane: { '@media (max-width: 600px)': { minHeight: 180 } },
  waveformSvg: { height: '80%', overflow: 'visible', width: '100%' },
  waveform: {
    fill: 'none',
    filter: 'drop-shadow(0 0 var(--signal-bloom) var(--signal-emission))',
    opacity: 'var(--signal-intensity)',
    stroke: 'var(--signal-emission)',
    strokeLinecap: 'square',
    strokeWidth: 'var(--signal-trace-width)',
  },
  waveformAfterimage: {
    opacity: 'calc((1 - var(--signal-focus)) * 0.5)',
    transform: 'translateY(7px)',
  },
  planeLabel: {
    bottom: 14,
    fontFamily: 'var(--guide-mono)',
    fontSize: '0.55rem',
    letterSpacing: '0.1em',
    position: 'absolute',
    textTransform: 'uppercase',
  },
  spectrum: { alignItems: 'end', display: 'flex', gap: 3, height: '82%' },
  spectrumBar: (height: string) => ({
    backgroundImage: 'linear-gradient(var(--signal-secondary), var(--signal-emission))',
    boxShadow: '0 0 calc(var(--signal-bloom) * 0.5) var(--signal-emission)',
    display: 'block',
    height,
    opacity: 'var(--signal-intensity)',
    transition: 'height var(--signal-decay) cubic-bezier(0.2, 0.8, 0.2, 1)',
    width: '100%',
  }),
  monitorButton: {
    backgroundColor: 'transparent',
    borderColor: 'var(--signal-emission)',
    borderStyle: 'solid',
    borderWidth: 1,
    color: 'var(--signal-secondary)',
    minHeight: 38,
    paddingInline: 14,
    textTransform: 'uppercase',
  },
  monitorActive: {
    backgroundColor: 'var(--signal-emission)',
    boxShadow: '0 0 var(--signal-bloom) var(--signal-emission)',
    color: 'var(--signal-background)',
  },
  kineticPreview: { minHeight: 620, padding: 'clamp(22px, 4vw, 48px)' },
  kineticSpecimen: { display: 'grid', gap: 18, textAlign: 'left', width: '100%' },
  feedbackButton: {
    backgroundColor: 'transparent',
    borderColor: 'var(--kinetic-foreground)',
    borderRadius: 'var(--kinetic-radius)',
    borderStyle: 'solid',
    borderWidth: 1,
    color: 'inherit',
    minHeight: 35,
    paddingInline: 12,
    textTransform: 'uppercase',
  },
  feedbackActive: { backgroundColor: 'var(--kinetic-accent)', color: 'var(--kinetic-background)' },
  mechanisms: {
    display: 'grid',
    gap: 14,
    gridTemplateColumns: '1fr 1fr',
    '@media (max-width: 600px)': { gridTemplateColumns: '1fr' },
  },
  mechanismPlane: {
    alignItems: 'center',
    borderColor: 'var(--guide-line)',
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: 330,
    padding: 18,
  },
  actuatorButton: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    minHeight: 120,
    minWidth: 'min(88%, 220px)',
    padding: 22,
  },
  actuatorTitle: { fontFamily: 'var(--guide-display)', fontSize: '2rem', marginTop: 7 },
  encoderControl: { alignItems: 'center', display: 'flex', gap: 12 },
  encoderStep: {
    backgroundColor: 'transparent',
    borderColor: 'var(--kinetic-foreground)',
    borderRadius: '50%',
    borderStyle: 'solid',
    borderWidth: 1,
    color: 'inherit',
    height: 32,
    width: 32,
  },
  encoder: {
    backgroundImage:
      'radial-gradient(circle at 35% 28%, color-mix(in srgb, var(--kinetic-background) 70%, white), var(--kinetic-background))',
    borderColor: 'var(--kinetic-foreground)',
    borderRadius: '50%',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow:
      '0 calc(var(--kinetic-travel) * 0.45) 0 color-mix(in srgb, var(--kinetic-foreground) 26%, transparent), 0 calc(var(--kinetic-travel) * 0.75) calc(var(--kinetic-mass) * 7px) color-mix(in srgb, var(--kinetic-foreground) 14%, transparent)',
    height: 112,
    position: 'relative',
    transition: 'transform var(--kinetic-duration) cubic-bezier(0.2, 1.35, 0.3, 1)',
    width: 112,
  },
  encoderRotation: (angle: number) => ({ transform: `rotate(${angle}deg)` }),
  encoderMark: {
    backgroundColor: 'var(--kinetic-accent)',
    height: 25,
    left: 'calc(50% - 1px)',
    position: 'absolute',
    top: 9,
    width: 3,
  },
  fader: {
    borderColor: 'var(--guide-line)',
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'grid',
    gap: 8,
    padding: 14,
  },
})

const styleMap: Readonly<Record<string, ReadonlyArray<Readonly<Record<string, unknown>>>>> = {
  'material-workbench': [workbenchStyles.root],
  'material-workbench-preview': [workbenchStyles.preview],
  'material-workbench-controls': [workbenchStyles.controls],
  'material-workbench-fields': [workbenchStyles.fields],
  'material-workbench-range': [workbenchStyles.field],
  'material-workbench-color': [workbenchStyles.field],
  'material-workbench-text': [workbenchStyles.field],
  'material-workbench-select': [workbenchStyles.field],
  'material-workbench-toggle': [workbenchStyles.toggle],
  'texture-workbench-specimen': [workbenchStyles.specimen],
  'print-workbench-specimen': [workbenchStyles.specimen],
  'signal-workbench-specimen': [workbenchStyles.signalSpecimen],
  'signal-instrument-row': [workbenchStyles.signalInstruments],
  'signal-waveform-plane': [workbenchStyles.signalPlane],
  'signal-spectrum-plane': [workbenchStyles.signalPlane, workbenchStyles.signalSpectrumPlane],
  'signal-waveform-afterimage': [workbenchStyles.waveformAfterimage],
  'kinetic-workbench-specimen': [workbenchStyles.kineticSpecimen],
  'kinetic-mechanisms': [workbenchStyles.mechanisms],
  'kinetic-actuator-plane': [workbenchStyles.mechanismPlane],
  'kinetic-encoder-plane': [workbenchStyles.mechanismPlane],
  'kinetic-encoder-control': [workbenchStyles.encoderControl],
  'kinetic-encoder': [workbenchStyles.encoder],
  'kinetic-fader': [workbenchStyles.fader],
}

export function workbenchClass(...names: readonly string[]) {
  return className(...names.flatMap((name) => styleMap[name] ?? []))
}
